"""
Base Code Generator
Abstract base class for all deployment code generators
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any


class ValidationError(ValueError):
    """Custom exception for validation errors."""
    pass


class ModelDataError(ValidationError):
    """Exception for model data validation errors."""
    pass


class OptimizationError(ValidationError):
    """Exception for optimization parameter errors."""
    pass


class BaseCodeGenerator(ABC):
    """Abstract base class for all code generators."""

    def __init__(self, model_data: Dict[str, Any], platform: str = 'arduino', optimization: str = 'balanced', overlap: float = 0.5):
        # Validate inputs before proceeding
        self._validate_model_data(model_data)
        self._validate_optimization(optimization)
        self._validate_platform(platform)

        self.model_data = model_data
        self.model_type = model_data.get('model_type', 'unknown')
        self.feature_names = model_data.get('feature_names', [])
        self.classes = model_data.get('classes', [])
        self.platform = platform
        self.optimization = optimization
        self.overlap = max(0.0, min(0.99, overlap))  # Clamp between 0-99%

        # Extract common parameters
        self.feature_means = model_data.get(
            'feature_means', [0.0] * len(self.feature_names))
        self.feature_stds = model_data.get(
            'feature_stds', [1.0] * len(self.feature_names))

        # Validate parameter consistency
        self._validate_parameter_consistency()

        # Set optimization-specific parameters
        self._set_optimization_parameters()

    def generate_header(self) -> str:
        """Generate common header file content."""
        header = f"""/*
 * Human Activity Recognition Model
 * Generated by HAR Edge Framework
 * Model Type: {self.model_type}
 * Features: {len(self.feature_names)}
 * Classes: {len(self.classes)}
 * Platform: {self.platform}
 * Optimization: {self.optimization.title()}
 * {self._get_optimization_comment()}
 */

#ifndef HAR_MODEL_H
#define HAR_MODEL_H

{self._get_platform_includes()}

// Model configuration
#define NUM_FEATURES {len(self.feature_names)}
#define NUM_CLASSES {len(self.classes)}
#define SAMPLING_RATE {self.sampling_rate}
#define WINDOW_SIZE {self.window_size}

{self._get_model_specific_declarations()}

// Optimization settings
#define FEATURE_PRECISION {self.feature_precision}
#define DEBUG_ENABLED {1 if self.debug_enabled else 0}
#define BUFFER_OPTIMIZATION {1 if self.buffer_optimization else 0}

{self._get_logging_macros()}

// Activity classes
{self._get_enum_or_define_classes()}

// Function declarations
{self._get_function_declarations()}

#endif // HAR_MODEL_H
"""
        return header.strip()

    def generate_implementation(self, header_filename: str = None) -> str:
        """Generate implementation file content with correct header include."""

        # Extract just the filename from the full path if provided
        if header_filename:
            # Get just the filename part (no path) for the #include
            import os
            header_include = os.path.basename(header_filename)
        else:
            # Fallback to generic name
            header_include = "har_model.h"

        implementation = f"""/*
 * Human Activity Recognition Model Implementation
 * Generated by HAR Edge Framework
 * Model Type: {self.model_type}
 * Trained Features: {len(self.feature_names)}
 * Platform: {self.platform}
 */

#include "{header_include}"
{self._get_impl_includes()}

// Forward declaration of internal prediction function
int har_predict_internal(float features[NUM_FEATURES]);

// Activity class names
const char* activity_names[NUM_CLASSES] = {{
    {', '.join([f'"{cls}"' for cls in self.classes])}
}};

{self._generate_feature_scaling_arrays()}

{self._generate_model_specific_implementation()}

void har_init() {{
    // Lightweight initialization function
    // Model is ready to use after this call
    // No Serial output here to avoid dependency issues
}}

// Safe prediction wrapper with input validation and feature scaling
int har_predict(float features[NUM_FEATURES]) {{
    // Input validation
    if (features == NULL) {{
        return -1; // Error: null pointer
    }}

    // Allocate array for scaled features
    float scaled_features[NUM_FEATURES];

    // Apply feature scaling: (x - mean) / std
    for (int i = 0; i < NUM_FEATURES; i++) {{
        // Check for valid feature values
        if (isnan(features[i]) || isinf(features[i])) {{
            features[i] = 0.0f; // Replace invalid values with zero
        }}

        // Apply StandardScaler transformation: (x - mean) / std
        float std = READ_STD(i);
        if (std < 0.0001f) std = 1.0f; // Prevent division by zero
        scaled_features[i] = (features[i] - READ_MEAN(i)) / std;

        // Clamp scaled features to reasonable range (after scaling)
        if (scaled_features[i] < -10.0f) scaled_features[i] = -10.0f;
        if (scaled_features[i] > 10.0f) scaled_features[i] = 10.0f;
    }}

    // Call model-specific prediction function with SCALED features
    int result = har_predict_internal(scaled_features);

    // Validate prediction result
    if (result < 0 || result >= NUM_CLASSES) {{
        return 0; // Return first class if invalid result
    }}

    return result;
}}

{self._generate_prediction_function()}

{self._generate_complete_feature_extraction()}

const char* get_activity_name(int class_id) {{
    if (class_id >= 0 && class_id < NUM_CLASSES) {{
        return activity_names[class_id];
    }}
    return "UNKNOWN";
}}

{self._generate_utility_functions()}
"""
        return implementation.strip()

    # ------------------------------------------------------------------
    # Platform-aware helpers for header / implementation generation
    # ------------------------------------------------------------------

    def _is_generic_platform(self) -> bool:
        """Return True if platform is a generic (non-Arduino) target."""
        return self.platform in ('generic_c', 'generic_cpp', 'esp_idf', 'zephyr')

    def _get_impl_includes(self) -> str:
        """Additional includes for the .c/.cpp implementation file."""
        if self.platform in ('generic_c',):
            return '#include <math.h>\n#include <stdlib.h>\n#include <stdio.h>'
        elif self.platform in ('generic_cpp',):
            return '#include <cmath>\n#include <cstdlib>\n#include <cstdio>'
        elif self.platform == 'esp_idf':
            return '#include <math.h>\n#include "esp_log.h"'
        else:
            return '#include <math.h>'

    def _get_platform_includes(self) -> str:
        """Return the appropriate #include directives for the target platform."""
        if self.platform in ('generic_c',):
            return (
                '#include <stdint.h>\n'
                '#include <stddef.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#include <float.h>'
            )
        elif self.platform in ('generic_cpp',):
            return (
                '#include <cstdint>\n'
                '#include <cstddef>\n'
                '#include <cmath>\n'
                '#include <cstring>\n'
                '#include <cfloat>'
            )
        elif self.platform == 'esp_idf':
            return (
                '#include <stdint.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#include "esp_log.h"\n'
                '#include "freertos/FreeRTOS.h"\n'
                '#include "freertos/task.h"'
            )
        elif self.platform == 'zephyr':
            return (
                '#include <stdint.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#include <zephyr/kernel.h>\n'
                '#include <zephyr/logging/log.h>'
            )
        elif self.platform == 'arm_cortex_m':
            return (
                '#include <stdint.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#ifdef __ARM_ARCH\n'
                '    #include "arm_math.h"\n'
                '#endif'
            )
        else:
            # Arduino / ESP32 / seeed_xiao / teensy
            return '#include <Arduino.h>'

    def _get_enum_or_define_classes(self) -> str:
        """Generate activity class constants — enum in C++, #defines in pure C."""
        # Sanitize class names for use as C identifiers
        safe_names = []
        for cls in self.classes:
            safe = cls.upper().replace(' ', '_').replace('-', '_')
            # Strip non-alnum/underscore chars
            safe = ''.join(c for c in safe if c.isalnum() or c == '_')
            if safe and safe[0].isdigit():
                safe = '_' + safe
            safe_names.append(safe)

        if self.platform == 'generic_c':
            # Pure C: use #define constants (no enum class)
            lines = [f'#define ACTIVITY_{name} {i}'
                     for i, name in enumerate(safe_names)]
            return '\n'.join(lines)
        else:
            entries = ', '.join([f'{name} = {i}' for i, name in enumerate(safe_names)])
            return f'enum ActivityClass {{\n    {entries}\n}};'

    def _get_function_declarations(self) -> str:
        """Generate function declarations appropriate for the platform language."""
        if self.platform == 'generic_c':
            return (
                '#ifdef __cplusplus\n'
                'extern "C" {\n'
                '#endif\n\n'
                'void har_init(void);\n'
                'int har_predict(float features[NUM_FEATURES]);\n'
                'void extract_features(float sensor_data[][6], int samples, float features[]);\n'
                'const char* get_activity_name(int class_id);\n\n'
                '#ifdef __cplusplus\n'
                '}\n'
                '#endif'
            )
        else:
            return (
                'void har_init();\n'
                'int har_predict(float features[NUM_FEATURES]);\n'
                'void extract_features(float sensor_data[][6], int samples, float features[]);\n'
                'const char* get_activity_name(int class_id);'
            )

    def _get_logging_macros(self) -> str:
        """Generate platform-portable logging macros.
        
        Provides HAR_LOG(fmt, ...) so utility/debug functions compile on all
        platforms without changing the body of the code.
        """
        if self.platform in ('generic_c', 'generic_cpp'):
            return (
                '// Platform-portable logging\n'
                '#include <stdio.h>\n'
                '#define HAR_LOG(fmt, ...) printf(fmt "\\n", ##__VA_ARGS__)\n'
                '#define HAR_LOG_FLOAT(label, val) printf("%s: %f\\n", (label), (double)(val))'
            )
        elif self.platform == 'esp_idf':
            return (
                '// Platform-portable logging\n'
                '#define HAR_LOG(fmt, ...) ESP_LOGI("HAR", fmt, ##__VA_ARGS__)\n'
                '#define HAR_LOG_FLOAT(label, val) ESP_LOGI("HAR", "%s: %f", (label), (double)(val))'
            )
        elif self.platform == 'zephyr':
            return (
                '// Platform-portable logging\n'
                'LOG_MODULE_REGISTER(har, LOG_LEVEL_INF);\n'
                '#define HAR_LOG(fmt, ...) LOG_INF(fmt, ##__VA_ARGS__)\n'
                '#define HAR_LOG_FLOAT(label, val) LOG_INF("%s: " #val, (label))'
            )
        else:
            # Arduino and Arduino-like (ESP32, Seeed XIAO, Teensy, ARM Cortex-M)
            return (
                '// Platform-portable logging (Arduino)\n'
                '#define HAR_LOG(fmt, ...) do { Serial.println(fmt); } while(0)\n'
                '#define HAR_LOG_FLOAT(label, val) do { Serial.print(label); Serial.print(": "); Serial.println(val, 4); } while(0)'
            )

    def _generate_feature_scaling_arrays(self) -> str:
        """Generate feature scaling arrays with real parameters.
        Uses PROGMEM on AVR platforms to store in flash instead of RAM."""
        precision = self.feature_precision
        
        # Use PROGMEM for AVR-based Arduino boards (limited RAM)
        progmem = 'PROGMEM ' if self.platform == 'arduino' else ''
        read_macro = self._needs_progmem_read()

        # Format all feature means
        means_formatted = []
        for i, mean in enumerate(self.feature_means):
            if i % 10 == 0 and i > 0:
                means_formatted.append(f'\n    {mean:.{precision}f}')
            else:
                means_formatted.append(f'{mean:.{precision}f}')
        means_array = ', '.join(means_formatted)

        # Format all feature stds
        stds_formatted = []
        for i, std in enumerate(self.feature_stds):
            if i % 10 == 0 and i > 0:
                stds_formatted.append(f'\n    {std:.{precision}f}')
            else:
                stds_formatted.append(f'{std:.{precision}f}')
        stds_array = ', '.join(stds_formatted)

        code = f"""// Feature scaling parameters (extracted from trained model)
// Precision: {precision} decimal places ({self.optimization} optimization)
const float feature_means[NUM_FEATURES] {progmem}= {{
    {means_array}
}};

const float feature_stds[NUM_FEATURES] {progmem}= {{
    {stds_array}
}};"""

        if read_macro:
            code += """

// Helper to read float from PROGMEM (AVR only)
static inline float pgm_read_float_near_safe(const float* addr) {
    float val;
    memcpy_P(&val, addr, sizeof(float));
    return val;
}
#define READ_MEAN(i) pgm_read_float_near_safe(&feature_means[i])
#define READ_STD(i) pgm_read_float_near_safe(&feature_stds[i])"""
        else:
            code += """

#define READ_MEAN(i) feature_means[i]
#define READ_STD(i) feature_stds[i]"""

        return code

    def _needs_progmem_read(self) -> bool:
        """Check if platform needs PROGMEM read macros (AVR only)."""
        return self.platform == 'arduino'

    def _generate_complete_feature_extraction(self) -> str:
        """Generate optimization-aware feature extraction function.
        
        CRITICAL: The feature extraction algorithm MUST match training exactly.
        Optimization level affects precision/sampling/window size, NOT the algorithm.
        If the model was trained with orientation-robust features, C++ MUST use
        orientation-robust extraction regardless of optimization level.
        """
        # Detect feature configuration from multiple sources
        orientation_robust = False
        include_per_axis = False
        include_frequency = False
        
        # Source 1: Explicit feature_config in model_info
        try:
            feature_config = self.model_data.get(
                'model_info', {}).get('feature_config', {})
            if feature_config:
                orientation_robust = feature_config.get(
                    'orientation_robust', False)
                include_per_axis = feature_config.get('include_per_axis', False)
                include_frequency = feature_config.get('include_frequency', False)
        except Exception:
            pass

        # Source 2: Legacy feature_method parameter
        try:
            feature_method = self.model_data.get(
                'model_params', {}).get('feature_method')
            if feature_method in ('orientation_invariant', 'orientation_invariant_time_only'):
                orientation_robust = True
        except Exception:
            pass

        # Source 3: Auto-detect from feature names (most reliable)
        if not orientation_robust and self.feature_names:
            has_acc_mag = any(str(name).startswith('acc_mag_') for name in self.feature_names)
            has_gyro_mag = any(str(name).startswith('gyro_mag_') for name in self.feature_names)
            has_jerk_mag = any(str(name).startswith('acc_jerk_mag_') for name in self.feature_names)
            if has_acc_mag and has_gyro_mag:
                orientation_robust = True
            # Also check for per-axis features
            has_per_axis = any(str(name).startswith(('aX_', 'aY_', 'aZ_', 'gX_', 'gY_', 'gZ_')) 
                             for name in self.feature_names)
            if has_per_axis:
                include_per_axis = True

        # Use orientation-robust features if configured
        if orientation_robust or feature_method == 'orientation_invariant':
            return self._generate_orientation_robust_extraction()

        # Per-axis feature extraction — ALWAYS extracts the same 15 features/axis
        # that match training, regardless of optimization level.
        # Optimization only affects computation method (precision, sorting algorithm)
        # but NEVER changes which features are produced.
        return self._generate_per_axis_extraction()

    # ------------------------------------------------------------------
    # Orientation-robust feature extraction (magnitude-based, 33 features)
    # ------------------------------------------------------------------

    def _generate_orientation_robust_extraction(self) -> str:
        """Generate orientation-robust (magnitude-based) feature extraction.
        
        Always produces the same 33 features regardless of optimization level.
        Optimization only affects computational shortcuts (e.g., sorting algorithm).
        """
        return """// Forward declaration for helper function
int extract_magnitude_stats(float* mag, int samples, float* features, int start_idx);

void extract_features(float sensor_data[][6], int samples, float features[]) {
    // Orientation-robust features (33 magnitude-based features)
    // Matches Python extract_orientation_invariant_features()
    // Features per magnitude (acc_mag, gyro_mag): mean, std, min, max, range, median, q25, q75, iqr,
    // skewness, kurtosis, rms, energy, zero_crossings, mean_crossing_rate (15 × 2 = 30)
    // Plus jerk magnitude: mean, std, max (3 features) = 33 total

    if (samples <= 1) {
        for (int i = 0; i < NUM_FEATURES; i++) features[i] = 0.0f;
        return;
    }

    // Temporary arrays for magnitude values
    float acc_mag[WINDOW_SIZE];
    float gyro_mag[WINDOW_SIZE];
    float jerk_mag[WINDOW_SIZE];

    // Calculate magnitude vectors
    float prev_ax = sensor_data[0][0];
    float prev_ay = sensor_data[0][1];
    float prev_az = sensor_data[0][2];

    for (int i = 0; i < samples; i++) {
        float ax = sensor_data[i][0];
        float ay = sensor_data[i][1];
        float az = sensor_data[i][2];
        float gx = sensor_data[i][3];
        float gy = sensor_data[i][4];
        float gz = sensor_data[i][5];

        acc_mag[i] = sqrtf(ax*ax + ay*ay + az*az);
        gyro_mag[i] = sqrtf(gx*gx + gy*gy + gz*gz);

        if (i > 0) {
            float dax = ax - prev_ax;
            float day = ay - prev_ay;
            float daz = az - prev_az;
            jerk_mag[i-1] = sqrtf(dax*dax + day*day + daz*daz);
        }

        prev_ax = ax; prev_ay = ay; prev_az = az;
    }

    int n_jerk = samples - 1;
    int idx = 0;

    // Extract 15 features from acc_mag
    idx = extract_magnitude_stats(acc_mag, samples, features, idx);

    // Extract 15 features from gyro_mag
    idx = extract_magnitude_stats(gyro_mag, samples, features, idx);

    // Extract 3 jerk magnitude features (mean, std, max)
    float jerk_sum = 0.0f, jerk_sum_sq = 0.0f, jerk_max = -1e9f;
    for (int i = 0; i < n_jerk; i++) {
        jerk_sum += jerk_mag[i];
        jerk_sum_sq += jerk_mag[i] * jerk_mag[i];
        if (jerk_mag[i] > jerk_max) jerk_max = jerk_mag[i];
    }

    float jerk_mean = (n_jerk > 0) ? (jerk_sum / n_jerk) : 0.0f;
    float jerk_var = (n_jerk > 0) ? ((jerk_sum_sq / n_jerk) - jerk_mean * jerk_mean) : 0.0f;
    float jerk_std = sqrtf(jerk_var > 0 ? jerk_var : 0.0f);

    features[idx++] = jerk_mean;
    features[idx++] = jerk_std;
    features[idx++] = jerk_max;

    // Fill remaining features with zeros
    for (; idx < NUM_FEATURES; idx++) features[idx] = 0.0f;
}

// Helper function to extract statistical features from magnitude vector
int extract_magnitude_stats(float* mag, int samples, float* features, int start_idx) {
    // Calculate all statistical features for one magnitude vector
    // Returns: mean, std, min, max, range, median, q25, q75, iqr,
    //          skewness, kurtosis, rms, energy, zero_crossings, mean_crossing_rate (15 features)

    int idx = start_idx;
    float n = (float)samples;

    // First pass: sum, sum_sq, min, max
    float sum = 0.0f, sum_sq = 0.0f;
    float min_val = 1e9f, max_val = -1e9f;
    for (int i = 0; i < samples; i++) {
        sum += mag[i];
        sum_sq += mag[i] * mag[i];
        if (mag[i] < min_val) min_val = mag[i];
        if (mag[i] > max_val) max_val = mag[i];
    }

    float mean = sum / n;
    float variance = (sum_sq / n) - (mean * mean);
    float std = sqrtf(variance > 0 ? variance : 0.0f);
    float rms = sqrtf(sum_sq / n);
    float energy = sum_sq;
    float range = max_val - min_val;

    features[idx++] = mean;         // 0: mean
    features[idx++] = std;          // 1: std
    features[idx++] = min_val;      // 2: min
    features[idx++] = max_val;      // 3: max
    features[idx++] = range;        // 4: range

    // Median and quartiles (requires sorting a copy)
    float sorted[WINDOW_SIZE];
    for (int i = 0; i < samples; i++) sorted[i] = mag[i];

    // Insertion sort (faster than bubble sort for small/partially-sorted arrays)
    for (int i = 1; i < samples; i++) {
        float key = sorted[i];
        int j = i - 1;
        while (j >= 0 && sorted[j] > key) {
            sorted[j + 1] = sorted[j];
            j--;
        }
        sorted[j + 1] = key;
    }

    float median = (samples % 2 == 0) ?
        (sorted[samples/2 - 1] + sorted[samples/2]) / 2.0f :
        sorted[samples/2];
    float q25 = sorted[samples/4];
    float q75 = sorted[(3*samples)/4];
    float iqr = q75 - q25;

    features[idx++] = median;       // 5: median
    features[idx++] = q25;          // 6: q25
    features[idx++] = q75;          // 7: q75
    features[idx++] = iqr;          // 8: iqr

    // Skewness and kurtosis - bias-corrected (pandas/scipy formula)
    // Use sample std (Bessel's correction) for standardization
    float sample_var = variance * n / (n - 1.0f + 0.001f);
    float sample_std = sqrtf(sample_var > 0 ? sample_var : 0.0001f);

    float m3_sum = 0.0f, m4_sum = 0.0f;
    for (int i = 0; i < samples; i++) {
        float z = (mag[i] - mean) / (sample_std + 0.0001f);
        float z2 = z * z;
        m3_sum += z * z2;
        m4_sum += z2 * z2;
    }

    // Skewness with bias correction: sqrt(n*(n-1))/(n-2) * (m3/n)
    float g1 = m3_sum / n;
    float skewness = 0.0f;
    if (samples >= 3) {
        skewness = sqrtf(n * (n - 1.0f)) / (n - 2.0f) * g1;
    }

    // Excess kurtosis with bias correction: (n-1)/((n-2)*(n-3)) * ((n+1)*g2 + 6)
    float g2 = m4_sum / n - 3.0f;
    float kurtosis = -3.0f;
    if (samples >= 4) {
        kurtosis = (n - 1.0f) / ((n - 2.0f) * (n - 3.0f)) * ((n + 1.0f) * g2 + 6.0f);
    }

    features[idx++] = skewness;     // 9: skewness
    features[idx++] = kurtosis;     // 10: kurtosis
    features[idx++] = rms;          // 11: rms
    features[idx++] = energy;       // 12: energy

    // Zero crossings and mean crossing rate
    int zero_crossings = 0;
    int mean_crossings = 0;
    for (int i = 1; i < samples; i++) {
        if ((mag[i-1] * mag[i]) < 0) zero_crossings++;
        if ((mag[i-1] - mean) * (mag[i] - mean) < 0) mean_crossings++;
    }

    features[idx++] = (float)zero_crossings;       // 13: zero_crossings
    features[idx++] = (float)mean_crossings / n;   // 14: mean_crossing_rate

    return idx;
}
"""

    # ------------------------------------------------------------------
    # Per-axis feature extraction (15 features × 6 axes = 90 features)
    # ------------------------------------------------------------------

    def _generate_per_axis_extraction(self) -> str:
        """Generate per-axis feature extraction that ALWAYS matches training.
        
        CRITICAL: All optimization levels produce the SAME 15 features per axis
        in the SAME order. The optimization level only affects:
          - Sorting algorithm (insertion sort vs bubble sort)
          - Floating-point precision (float vs double accumulation)
          - Input validation strictness
        It NEVER changes which features are extracted.
        """
        # Use double-precision accumulation for accuracy mode
        use_double = self.optimization == 'accuracy'
        acc_type = 'double' if use_double else 'float'

        return f"""void extract_features(float sensor_data[][6], int samples, float features[]) {{
    // Per-axis feature extraction — 15 features per axis × 6 axes = 90 features
    // MUST match training feature extraction exactly regardless of optimization level.
    // Optimization: {self.optimization.upper()} ({'double-precision' if use_double else 'single-precision'} accumulation)

    // Input validation
    if (samples <= 1 || samples > WINDOW_SIZE) {{
        for (int i = 0; i < NUM_FEATURES; i++) features[i] = 0.0f;
        return;
    }}

    int feature_idx = 0;

    // For each sensor axis (aX, aY, aZ, gX, gY, gZ)
    for (int axis = 0; axis < 6; axis++) {{
        // Copy data for sorting (used for median and quartiles)
        float sorted_data[WINDOW_SIZE];
        for (int i = 0; i < samples; i++) {{
            sorted_data[i] = sensor_data[i][axis];
        }}

        // Insertion sort — O(n²) worst case but fast for small/partially-sorted arrays
        for (int i = 1; i < samples; i++) {{
            float key = sorted_data[i];
            int j = i - 1;
            while (j >= 0 && sorted_data[j] > key) {{
                sorted_data[j + 1] = sorted_data[j];
                j--;
            }}
            sorted_data[j + 1] = key;
        }}

        // Statistical calculations
        {acc_type} sum = 0, sum_sq = 0;
        float min_val = sensor_data[0][axis];
        float max_val = sensor_data[0][axis];

        for (int i = 0; i < samples; i++) {{
            {acc_type} val = ({acc_type})sensor_data[i][axis];
            sum += val;
            sum_sq += val * val;
            if (sensor_data[i][axis] < min_val) min_val = sensor_data[i][axis];
            if (sensor_data[i][axis] > max_val) max_val = sensor_data[i][axis];
        }}

        float n = (float)samples;
        float mean = (float)(sum / n);
        float variance = (float)((sum_sq / n) - (({acc_type})mean * ({acc_type})mean));
        if (variance < 0.0f) variance = 0.0f;
        float std_dev = sqrtf(variance);

        // Median and quartiles from sorted data
        int mid = samples / 2;
        float median = (samples % 2 == 0)
            ? (sorted_data[mid - 1] + sorted_data[mid]) / 2.0f
            : sorted_data[mid];
        float q25 = sorted_data[samples / 4];
        float q75 = sorted_data[(3 * samples) / 4];
        float iqr = q75 - q25;

        // Feature vector (same 15 features in same order as training)
        features[feature_idx++] = mean;                          // 0: mean
        features[feature_idx++] = std_dev;                       // 1: std
        features[feature_idx++] = min_val;                       // 2: min
        features[feature_idx++] = max_val;                       // 3: max
        features[feature_idx++] = max_val - min_val;             // 4: range
        features[feature_idx++] = median;                        // 5: median
        features[feature_idx++] = q25;                           // 6: q25
        features[feature_idx++] = q75;                           // 7: q75
        features[feature_idx++] = iqr;                           // 8: iqr

        // Skewness and kurtosis — bias-corrected (pandas/scipy formula)
        float sample_std = sqrtf(variance * n / (n - 1.0f + 0.001f));

        float m3_sum = 0.0f, m4_sum = 0.0f;
        for (int i = 0; i < samples; i++) {{
            float z = (sensor_data[i][axis] - mean) / (sample_std + 0.001f);
            float z2 = z * z;
            m3_sum += z * z2;
            m4_sum += z2 * z2;
        }}

        // Skewness with bias correction
        float g1 = m3_sum / n;
        float skewness = 0.0f;
        if (samples >= 3) {{
            skewness = sqrtf(n * (n - 1.0f)) / (n - 2.0f) * g1;
        }}

        // Excess kurtosis with bias correction
        float g2 = m4_sum / n - 3.0f;
        float kurtosis = -3.0f;
        if (samples >= 4) {{
            kurtosis = (n - 1.0f) / ((n - 2.0f) * (n - 3.0f)) * ((n + 1.0f) * g2 + 6.0f);
        }}

        features[feature_idx++] = skewness;                     // 9: skewness
        features[feature_idx++] = kurtosis;                      // 10: kurtosis
        features[feature_idx++] = sqrtf((float)(sum_sq / n));    // 11: rms
        features[feature_idx++] = (float)sum_sq;                 // 12: energy

        // Zero-crossings (signal crosses zero)
        int zero_crossings = 0;
        for (int i = 1; i < samples; i++) {{
            if (sensor_data[i-1][axis] * sensor_data[i][axis] < 0)
                zero_crossings++;
        }}
        features[feature_idx++] = (float)zero_crossings;        // 13: zero_crossings

        // Mean-crossing rate (normalised)
        int mean_crossings = 0;
        for (int i = 1; i < samples; i++) {{
            if ((sensor_data[i-1][axis] - mean) * (sensor_data[i][axis] - mean) < 0)
                mean_crossings++;
        }}
        features[feature_idx++] = (float)mean_crossings / n;    // 14: mean_crossing_rate
    }}

    // Total: 15 features/axis × 6 axes = 90 time-domain features
    // Fill any remaining slots (should be zero if calculation is correct)
    while (feature_idx < NUM_FEATURES) {{
        features[feature_idx++] = 0.0f;
    }}
}}"""

    @abstractmethod
    def _get_model_specific_declarations(self) -> str:
        """Generate model-specific declarations for header file."""
        pass

    @abstractmethod
    def _generate_model_specific_implementation(self) -> str:
        """Generate model-specific implementation code."""
        pass

    @abstractmethod
    def _generate_prediction_function(self) -> str:
        """Generate model-specific prediction function."""
        pass

    @abstractmethod
    def _generate_utility_functions(self) -> str:
        """Generate model-specific utility functions."""
        pass

    def generate_example_sketch(self, header_filename: str = None) -> str:
        """Generate platform-appropriate example code."""

        # Extract just the filename from the full path if provided
        if header_filename:
            import os
            header_include = os.path.basename(header_filename)
        else:
            header_include = "har_model.h"

        # Dispatch to platform-specific example generators
        if self.platform in ('generic_c', 'generic_cpp'):
            return self._generate_generic_example(header_include)
        elif self.platform == 'esp_idf':
            return self._generate_esp_idf_example(header_include)
        else:
            return self._generate_arduino_example(header_include)

    def _generate_generic_example(self, header_include: str) -> str:
        """Generate a portable C/C++ main() example (no Arduino dependency)."""
        is_cpp = self.platform == 'generic_cpp'
        ext = 'cpp' if is_cpp else 'c'
        io_include = '<cstdio>' if is_cpp else '<stdio.h>'
        math_include = '<cmath>' if is_cpp else '<math.h>'
        stdlib_include = '<cstdlib>' if is_cpp else '<stdlib.h>'

        return f"""/*
 * HAR Model — Portable {('C++' if is_cpp else 'C')} Example
 * Model Type: {self.model_type}
 * Optimization: {self.optimization.upper()}
 *
 * Compile:
 *   {'g++' if is_cpp else 'gcc'} -O2 -o har_example example.{ext} har_model.{ext} -lm
 *
 * This file demonstrates how to call the generated HAR model from
 * a plain {('C++' if is_cpp else 'C')} program.  Replace the dummy sensor data
 * with your actual sensor reading code.
 */

#include "{header_include}"
#include {io_include}
#include {math_include}
#include {stdlib_include}

/* ------------------------------------------------------------------ */
/*  Provide your sensor data here                                      */
/* ------------------------------------------------------------------ */

/**
 * Fill sensor_data[WINDOW_SIZE][6] with one window of IMU readings.
 * Columns: aX, aY, aZ (m/s²), gX, gY, gZ (deg/s or rad/s)
 * Return 0 on success, non-zero on error.
 */
static int read_sensor_window(float sensor_data[][6]) {{
    /* --- REPLACE with actual sensor/file reading code --- */
    for (int i = 0; i < WINDOW_SIZE; i++) {{
        sensor_data[i][0] = 0.0f;   /* aX */
        sensor_data[i][1] = 0.0f;   /* aY */
        sensor_data[i][2] = 9.81f;  /* aZ (gravity) */
        sensor_data[i][3] = 0.0f;   /* gX */
        sensor_data[i][4] = 0.0f;   /* gY */
        sensor_data[i][5] = 0.0f;   /* gZ */
    }}
    return 0;
}}

/* ------------------------------------------------------------------ */

int main({"void" if not is_cpp else ""}) {{
    printf("HAR Model — {self.model_type.upper()} ({self.optimization.title()})\\n");
    printf("Features: %d | Classes: %d | Window: %d samples @ %d Hz\\n",
           NUM_FEATURES, NUM_CLASSES, WINDOW_SIZE, SAMPLING_RATE);

    har_init();

    float sensor_data[WINDOW_SIZE][6];
    float features[NUM_FEATURES];

    /* Main inference loop — run until interrupted */
    int iteration = 0;
    while (iteration < 10) {{  /* Change to 'while(1)' for continuous operation */
        if (read_sensor_window(sensor_data) != 0) {{
            printf("Error reading sensor data\\n");
            return 1;
        }}

        extract_features(sensor_data, WINDOW_SIZE, features);

        int predicted_class = har_predict(features);
        const char* activity = get_activity_name(predicted_class);

        printf("[%04d] Predicted: %s (class %d)\\n",
               iteration, activity, predicted_class);
        iteration++;
    }}

    printf("Done.\\n");
    return 0;
}}
"""

    def _generate_esp_idf_example(self, header_include: str) -> str:
        """Generate an ESP-IDF app_main() example."""
        return f"""/*
 * HAR Model — ESP-IDF Example
 * Model Type: {self.model_type}
 * Optimization: {self.optimization.upper()}
 *
 * Place in main/main.c of your ESP-IDF project.
 * Build: idf.py build
 * Flash: idf.py flash monitor
 */

#include "{header_include}"
#include <stdio.h>
#include <math.h>
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2c.h"

static const char* TAG = "HAR";

/* ------------------------------------------------------------------ */
/*  Replace with your sensor driver                                    */
/* ------------------------------------------------------------------ */
static int read_sensor_window(float sensor_data[][6]) {{
    /* TODO: Read {self.window_size} samples from IMU via I2C/SPI */
    for (int i = 0; i < WINDOW_SIZE; i++) {{
        sensor_data[i][0] = 0.0f;
        sensor_data[i][1] = 0.0f;
        sensor_data[i][2] = 9.81f;
        sensor_data[i][3] = 0.0f;
        sensor_data[i][4] = 0.0f;
        sensor_data[i][5] = 0.0f;
    }}
    return 0;
}}

void app_main(void) {{
    ESP_LOGI(TAG, "HAR Model — {self.model_type.upper()} ({self.optimization.title()})");
    ESP_LOGI(TAG, "Features: %d | Classes: %d | Window: %d @ %d Hz",
             NUM_FEATURES, NUM_CLASSES, WINDOW_SIZE, SAMPLING_RATE);

    har_init();

    float sensor_data[WINDOW_SIZE][6];
    float features[NUM_FEATURES];

    while (1) {{
        if (read_sensor_window(sensor_data) != 0) {{
            ESP_LOGE(TAG, "Sensor read error");
            vTaskDelay(pdMS_TO_TICKS(1000));
            continue;
        }}

        extract_features(sensor_data, WINDOW_SIZE, features);
        int predicted_class = har_predict(features);
        const char* activity = get_activity_name(predicted_class);

        ESP_LOGI(TAG, "Predicted: %s (class %d)", activity, predicted_class);

        vTaskDelay(pdMS_TO_TICKS({int(1000 * self.window_size / self.sampling_rate)}));
    }}
}}
"""

    def _generate_arduino_example(self, header_include: str) -> str:
        """Generate optimization-aware Arduino sketch with correct header include."""

        header_include = header_include or "har_model.h"

        # Optimization-specific delay and settings
        delay_ms = {
            'speed': 5,      # Fast sampling for speed optimization
            'power': 50,     # Slower sampling for power efficiency
            'accuracy': 10,  # Moderate sampling for accuracy
            'balanced': 10   # Standard sampling
        }.get(self.optimization, 10)

        reading_interval = 1000 // self.sampling_rate

        # Platform-specific IMU initialization code
        platform_code = self._get_platform_specific_code()

        sketch_code = f"""/*
 * HAR Model Example Sketch
 * Demonstrates usage of the generated HAR model
 * Model Type: {self.model_type}
 * Optimization: {self.optimization.upper()}
 * {self._get_optimization_comment()}
 */

#include "{header_include}"

{platform_code['includes']}

{platform_code['defines']}

// Data collection variables
float sensor_buffer[WINDOW_SIZE][6];  // aX, aY, aZ, gX, gY, gZ
int buffer_index = 0;
float features[NUM_FEATURES];
unsigned long last_reading = 0;
const unsigned long READING_INTERVAL = {reading_interval}; // ms between readings

{platform_code['overlap_defines']}

void setup() {{
    Serial.begin(115200);
    while (!Serial)
        delay(10);

    // Print optimization info
    Serial.println("HAR Model - {self.optimization.title()} Optimization");
    Serial.println("========================================");
    Serial.println("Configuration:");
    Serial.print("  Sampling Rate: ");
    Serial.print(SAMPLING_RATE);
    Serial.println(" Hz");
    Serial.print("  Window Size: ");
    Serial.print(WINDOW_SIZE);
    Serial.println(" samples");
    Serial.print("  Features: ");
    Serial.println(NUM_FEATURES);
    Serial.print("  Optimization: ");
    Serial.println("{self.optimization.title()}");

    // Initialize HAR model
    har_init();

{platform_code['imu_init']}

    Serial.println("HAR Model Ready!");
    Serial.println("Collecting sensor data...");
}}

void loop() {{
    unsigned long current_time = millis();

    // Check if it's time for a new reading
    if (current_time - last_reading >= READING_INTERVAL) {{
        last_reading = current_time;

{platform_code['sensor_read']}

        // Store in buffer
        sensor_buffer[buffer_index][0] = aX;
        sensor_buffer[buffer_index][1] = aY;
        sensor_buffer[buffer_index][2] = aZ;
        sensor_buffer[buffer_index][3] = gX;
        sensor_buffer[buffer_index][4] = gY;
        sensor_buffer[buffer_index][5] = gZ;

        buffer_index++;

        // When buffer is full, extract features and predict
        if (buffer_index >= WINDOW_SIZE) {{
            // Use overlap for smoother predictions
            for (int i = 0; i < WINDOW_SIZE / 2; i++) {{
                for (int axis = 0; axis < 6; axis++) {{
                    sensor_buffer[i][axis] = sensor_buffer[i + WINDOW_SIZE / 2][axis];
                }}
            }}
            buffer_index = (int)buffer_index_shift;

{platform_code['motion_stats']}

            // Extract features
            extract_features(sensor_buffer, WINDOW_SIZE, features);

            // Make prediction
            int predicted_class = har_predict(features);
            const char* activity_name = get_activity_name(predicted_class);

{platform_code['print_result']}
        }}
    }}

    delay({delay_ms});  // Optimization-specific delay
}}"""

        return sketch_code

    def _get_platform_specific_code(self) -> dict:
        """Get platform-specific code snippets for IMU initialization and sensor reading."""

        if self.platform == 'seeed_xiao':
            return {
                'includes': """#include <LSM6DS3.h>
#include <Wire.h>

//Create a instance of class LSM6DS3
LSM6DS3 myIMU(I2C_MODE, 0x6A);  //I2C device address 0x6A""",
                'defines': """/* Constant defines -------------------------------------------------------- */
#define CONVERT_G_TO_MS2 9.80665f
#define MAX_ACCEPTED_RANGE 2.0f  // starting 03/2022, models are generated setting range to +-2, but this example use Arudino library which set range to +-4g. If you are using an older model, ignore this value and use 4.0f instead""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const float buffer_index_shift = WINDOW_SIZE * (1 - OVERLAP);""",
                'imu_init': """    // Initialize I2C bus first
    Wire.begin();
    delay(100);  // Give I2C time to stabilize

    // Initialize IMU sensor
    Serial.println("Initializing IMU sensor...");

    // LSM6DS3 begin() returns 0 on SUCCESS, non-zero on failure
    if (myIMU.begin() != 0) {
        Serial.println("❌ Failed to initialize IMU!");
        Serial.println("Trying alternate I2C address 0x6B...");

        // Try alternate address
        LSM6DS3 myIMU_alt(I2C_MODE, 0x6B);
        if (myIMU_alt.begin() != 0) {
            Serial.println("❌ IMU not found at 0x6A or 0x6B");
            Serial.println("Check I2C connections and power");
            while (1) {
                delay(100);  // Halt - cannot continue without IMU
            }
        } else {
            Serial.println("✅ IMU found at address 0x6B!");
            // Note: You'll need to update the global myIMU object address
        }
    } else {
        Serial.println("✅ IMU initialized successfully at 0x6A!");
    }

    // Print IMU settings
    Serial.print("Accelerometer range: ±");
    Serial.print(MAX_ACCEPTED_RANGE);
    Serial.println("g");""",
                'sensor_read': """        // Read sensor data from IMU
        float aX = myIMU.readFloatAccelX() * CONVERT_G_TO_MS2;
        float aY = myIMU.readFloatAccelY() * CONVERT_G_TO_MS2;
        float aZ = myIMU.readFloatAccelZ() * CONVERT_G_TO_MS2;
        float gX = myIMU.readFloatGyroX();
        float gY = myIMU.readFloatGyroY();
        float gZ = myIMU.readFloatGyroZ();""",
                'motion_stats': """            // Calculate motion statistics for debugging
            float acc_mag_sum = 0, gyro_mag_sum = 0;
            for (int i = 0; i < WINDOW_SIZE; i++) {
                float acc_mag = sqrt(sensor_buffer[i][0] * sensor_buffer[i][0] +
                                     sensor_buffer[i][1] * sensor_buffer[i][1] +
                                     sensor_buffer[i][2] * sensor_buffer[i][2]);
                float gyro_mag = sqrt(sensor_buffer[i][3] * sensor_buffer[i][3] +
                                      sensor_buffer[i][4] * sensor_buffer[i][4] +
                                      sensor_buffer[i][5] * sensor_buffer[i][5]);
                acc_mag_sum += acc_mag;
                gyro_mag_sum += gyro_mag;
            }
            float avg_acc_mag = acc_mag_sum / WINDOW_SIZE;
            float avg_gyro_mag = gyro_mag_sum / WINDOW_SIZE;""",
                'print_result': """            // Print result with motion statistics
            Serial.print("Motion: acc=");
            Serial.print(avg_acc_mag, 2);
            Serial.print(" gyro=");
            Serial.print(avg_gyro_mag, 2);
            Serial.print(" => Predicted: ");
            Serial.print(activity_name);
            Serial.print(" (Class ");
            Serial.print(predicted_class);
            Serial.println(")");"""
            }

        elif self.platform == 'esp32':
            # ESP32 with MPU6050/MPU6886
            return {
                'includes': """#include <Wire.h>
#include "MPU6886.h"  // or MPU6050.h depending on your sensor

MPU6886 IMU;  // Create IMU instance""",
                'defines': """#define CONVERT_G_TO_MS2 9.80665f""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const int buffer_index_shift = (int)(WINDOW_SIZE * (1 - OVERLAP));""",
                'imu_init': """    // Initialize I2C
    Wire.begin();

    // Initialize IMU sensor
    Serial.println("Initializing IMU sensor...");
    if (IMU.Init() != 0) {
        Serial.println("❌ Failed to initialize IMU!");
        while (1) delay(100);
    }
    Serial.println("✅ IMU initialized successfully!");""",
                'sensor_read': """        // Read sensor data
        float aX, aY, aZ, gX, gY, gZ;
        IMU.getAccelData(&aX, &aY, &aZ);
        IMU.getGyroData(&gX, &gY, &gZ);

        // Convert to m/s²
        aX *= CONVERT_G_TO_MS2;
        aY *= CONVERT_G_TO_MS2;
        aZ *= CONVERT_G_TO_MS2;""",
                'motion_stats': """            // Optional: Calculate motion magnitude for debugging
            float acc_mag = sqrt(sensor_buffer[WINDOW_SIZE-1][0] * sensor_buffer[WINDOW_SIZE-1][0] +
                               sensor_buffer[WINDOW_SIZE-1][1] * sensor_buffer[WINDOW_SIZE-1][1] +
                               sensor_buffer[WINDOW_SIZE-1][2] * sensor_buffer[WINDOW_SIZE-1][2]);""",
                'print_result': """            // Print result
            Serial.print("Predicted: ");
            Serial.print(activity_name);
            Serial.print(" (Class ");
            Serial.print(predicted_class);
            Serial.println(")");"""
            }

        else:  # Generic Arduino
            return {
                'includes': """// Include your IMU library here
// #include <Adafruit_MPU6050.h>
// #include <Adafruit_Sensor.h>
#include <Wire.h>""",
                'defines': """#define CONVERT_G_TO_MS2 9.80665f""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const int buffer_index_shift = (int)(WINDOW_SIZE * (1 - OVERLAP));""",
                'imu_init': """    // Initialize I2C
    Wire.begin();

    // Initialize IMU sensor
    Serial.println("Initializing IMU sensor...");
    // Add your IMU initialization code here
    Serial.println("✅ IMU initialized!");""",
                'sensor_read': """        // Read sensor data (replace with your IMU library calls)
        float aX = 0.0f;  // Replace with actual accelerometer X
        float aY = 0.0f;  // Replace with actual accelerometer Y
        float aZ = 9.8f;  // Replace with actual accelerometer Z
        float gX = 0.0f;  // Replace with actual gyroscope X
        float gY = 0.0f;  // Replace with actual gyroscope Y
        float gZ = 0.0f;  // Replace with actual gyroscope Z""",
                'motion_stats': """            // Optional: Add motion statistics here""",
                'print_result': """            // Print result
            Serial.print("Predicted: ");
            Serial.print(activity_name);
            Serial.print(" (Class ");
            Serial.print(predicted_class);
            Serial.println(")");"""
            }

    def _set_optimization_parameters(self):
        """Set parameters based on optimization strategy and model complexity."""
        # Calculate complexity factors
        num_features = len(self.feature_names)
        num_classes = len(self.classes)
        complexity_factor = self._calculate_complexity_factor()

        if self.optimization == 'accuracy':
            self.sampling_rate = 100  # Higher sampling for better accuracy
            self.window_size = min(
                100, max(50, int(100 * complexity_factor)))  # Adaptive window
            self.feature_precision = 6  # Higher precision for features
            self.debug_enabled = True  # Enable detailed debugging
            self.buffer_optimization = False
        elif self.optimization == 'speed':
            # Adaptive speed optimization based on complexity
            base_sampling = 50
            if complexity_factor > 2.0:  # Very complex model
                self.sampling_rate = max(25, int(base_sampling / 1.5))
            elif complexity_factor > 1.5:  # Moderately complex
                self.sampling_rate = max(30, int(base_sampling / 1.2))
            else:
                self.sampling_rate = base_sampling

            self.window_size = min(50, max(25, int(50 / complexity_factor)))
            self.feature_precision = max(2, min(3, int(4 - complexity_factor)))
            self.debug_enabled = False  # Disable debugging for speed
            self.buffer_optimization = True
        elif self.optimization == 'power':
            # Ultra-conservative for power, more aggressive for complex models
            base_sampling = 25
            if complexity_factor > 2.0:  # Very complex model
                self.sampling_rate = max(15, int(base_sampling / 1.5))
            else:
                self.sampling_rate = base_sampling

            self.window_size = min(50, max(20, int(40 / complexity_factor)))
            # Increased min precision from 1 to 3 - scaler values are tiny (0.004-0.017)
            # and rounding to 1 decimal makes them all 0.0, breaking normalization
            self.feature_precision = max(3, min(4, int(5 - complexity_factor)))
            self.debug_enabled = False  # No debugging to save power
            self.buffer_optimization = True
        else:  # balanced
            # Balanced approach - use 100 Hz for consistency with training data
            # Window size of 150 samples = 1.5 seconds at 100 Hz
            self.sampling_rate = 100  # Standard sampling rate for HAR
            # 1.5 second windows (increased from 75 for better accuracy)
            self.window_size = 150
            self.feature_precision = 3  # Balanced precision
            self.debug_enabled = False  # No debugging by default
            self.buffer_optimization = False

        # Apply final bounds checking
        self.sampling_rate = max(10, min(200, self.sampling_rate))
        self.window_size = max(20, min(200, self.window_size))
        self.feature_precision = max(1, min(8, self.feature_precision))

    def _calculate_complexity_factor(self) -> float:
        """
        Calculate model complexity factor based on features, classes, and model type.

        Returns:
            Float representing relative complexity (1.0 = baseline, >1.0 = more complex)
        """
        num_features = len(self.feature_names)
        num_classes = len(self.classes)

        # Base complexity from features and classes
        feature_factor = num_features / 50.0  # Normalize around 50 features
        class_factor = num_classes / 4.0      # Normalize around 4 classes

        # Model-type specific complexity multipliers
        model_multipliers = {
            'neural_network': 1.5,   # Neural networks are more complex
            'random_forest': 1.2,    # Random forests are moderately complex
            'svm': 1.3,              # SVMs can be complex
            'unknown': 1.0           # Default
        }

        model_multiplier = model_multipliers.get(self.model_type, 1.0)

        # Calculate overall complexity
        complexity = (feature_factor + class_factor) * model_multiplier / 2.0

        # Apply reasonable bounds
        return max(0.5, min(5.0, complexity))

    def _get_optimization_comment(self) -> str:
        """Get optimization-specific comment for generated code."""
        optimization_descriptions = {
            'accuracy': 'Optimized for maximum accuracy - higher sampling rate and precision',
            'speed': 'Optimized for fast inference - reduced sampling and simplified calculations',
            'power': 'Optimized for power efficiency - minimal sampling and low-power operations',
            'balanced': 'Balanced optimization - good trade-off between accuracy, speed, and power'
        }
        return optimization_descriptions.get(self.optimization, 'Standard configuration')

    def _validate_model_data(self, model_data: Dict[str, Any]) -> None:
        """
        Validate required model data fields and consistency.

        Args:
            model_data: Dictionary containing model parameters

        Raises:
            ModelDataError: If validation fails
        """
        if not isinstance(model_data, dict):
            raise ModelDataError("model_data must be a dictionary")

        # Check required fields
        required_fields = ['model_type', 'feature_names', 'classes']
        for field in required_fields:
            if field not in model_data:
                raise ModelDataError(f"Missing required field: '{field}'")

            value = model_data[field]
            if value is None:
                raise ModelDataError(f"Field '{field}' cannot be None")

            if field in ['feature_names', 'classes'] and not value:
                raise ModelDataError(f"Field '{field}' cannot be empty")

        # Validate model_type
        valid_model_types = ['random_forest',
                             'neural_network', 'svm', 'arm_cortex_m']
        if model_data['model_type'] not in valid_model_types:
            raise ModelDataError(f"Invalid model_type: '{model_data['model_type']}'. "
                                 f"Valid types: {valid_model_types}")

        # Validate feature_names
        feature_names = model_data['feature_names']
        if not isinstance(feature_names, list):
            raise ModelDataError("feature_names must be a list")

        if len(feature_names) < 1:
            raise ModelDataError("At least one feature is required")

        if len(feature_names) > 1000:
            raise ModelDataError("Too many features (max 1000 supported)")

        # Check for duplicate feature names
        if len(set(feature_names)) != len(feature_names):
            raise ModelDataError("Duplicate feature names are not allowed")

        # Validate classes
        classes = model_data['classes']
        if not isinstance(classes, list):
            raise ModelDataError("classes must be a list")

        if len(classes) < 2:
            raise ModelDataError(
                "At least two classes are required for classification")

        if len(classes) > 100:
            raise ModelDataError("Too many classes (max 100 supported)")

        # Check for duplicate class names
        if len(set(classes)) != len(classes):
            raise ModelDataError("Duplicate class names are not allowed")

    def _validate_optimization(self, optimization: str) -> None:
        """
        Validate optimization parameter.

        Args:
            optimization: Optimization level string

        Raises:
            OptimizationError: If validation fails
        """
        if not isinstance(optimization, str):
            raise OptimizationError("optimization must be a string")

        valid_optimizations = ['accuracy', 'speed', 'power', 'balanced']
        if optimization not in valid_optimizations:
            raise OptimizationError(f"Invalid optimization: '{optimization}'. "
                                    f"Valid options: {valid_optimizations}")

    def _validate_platform(self, platform: str) -> None:
        """
        Validate platform parameter.

        Args:
            platform: Target platform string

        Raises:
            ValidationError: If validation fails
        """
        if not isinstance(platform, str):
            raise ValidationError("platform must be a string")

        valid_platforms = ['arduino', 'arm_cortex_m',
                           'esp32', 'teensy', 'seeed_xiao',
                           'generic_c', 'generic_cpp', 'esp_idf',
                           'micropython', 'zephyr']
        if platform not in valid_platforms:
            raise ValidationError(f"Invalid platform: '{platform}'. "
                                  f"Valid platforms: {valid_platforms}")

    def _validate_parameter_consistency(self) -> None:
        """
        Validate consistency between different model parameters.

        Raises:
            ModelDataError: If parameters are inconsistent
        """
        # Check feature scaling parameter consistency
        if 'feature_means' in self.model_data:
            means = self.model_data['feature_means']
            if not isinstance(means, list):
                raise ModelDataError("feature_means must be a list")

            if len(means) != len(self.feature_names):
                raise ModelDataError(f"feature_means length ({len(means)}) must match "
                                     f"feature_names length ({len(self.feature_names)})")

        if 'feature_stds' in self.model_data:
            stds = self.model_data['feature_stds']
            if not isinstance(stds, list):
                raise ModelDataError("feature_stds must be a list")

            if len(stds) != len(self.feature_names):
                raise ModelDataError(f"feature_stds length ({len(stds)}) must match "
                                     f"feature_names length ({len(self.feature_names)})")

            # Check for zero or negative standard deviations
            for i, std in enumerate(stds):
                if not isinstance(std, (int, float)) or std <= 0:
                    raise ModelDataError(
                        f"feature_stds[{i}] must be a positive number, got {std}")
