"""
Base Code Generator
Abstract base class for all deployment code generators
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any


class ValidationError(ValueError):
    """Custom exception for validation errors."""
    pass


class ModelDataError(ValidationError):
    """Exception for model data validation errors."""
    pass


class OptimizationError(ValidationError):
    """Exception for optimization parameter errors."""
    pass


class BaseCodeGenerator(ABC):
    """Abstract base class for all code generators."""

    def __init__(self, model_data: Dict[str, Any], platform: str = 'arduino',
                 optimization: str = 'balanced', overlap: float = 0.5,
                 quantization: str = 'none',
                 confidence_threshold: float = 0.6,
                 smoothing_window: int = 1,
                 enable_iir_filter: bool = False):
        # Validate inputs before proceeding
        self._validate_model_data(model_data)
        self._validate_optimization(optimization)
        self._validate_platform(platform)

        self.model_data = model_data
        self.model_type = model_data.get('model_type', 'unknown')
        self.feature_names = model_data.get('feature_names', [])
        self.classes = model_data.get('classes', [])
        self.platform = platform
        self.optimization = optimization
        self.overlap = max(0.0, min(0.99, overlap))  # Clamp between 0-99%
        self.confidence_threshold = max(0.0, min(1.0, confidence_threshold))
        self.smoothing_window = max(1, min(9, smoothing_window))
        self.enable_iir_filter = enable_iir_filter

        # Quantization mode: 'none', 'int8', 'int16', 'float16'
        from .quantization import QUANTIZATION_MODES
        self.quantization = quantization if quantization in QUANTIZATION_MODES else 'none'

        # Extract common parameters
        self.feature_means = model_data.get(
            'feature_means', [0.0] * len(self.feature_names))
        self.feature_stds = model_data.get(
            'feature_stds', [1.0] * len(self.feature_names))

        # Extract preprocessing config from fe_config
        model_info = model_data.get('model_info', {})
        fe_config = model_info.get('fe_config', {})
        self.preprocessing = fe_config.get('preprocessing', {})

        # Validate parameter consistency
        self._validate_parameter_consistency()

        # Set optimization-specific parameters
        self._set_optimization_parameters()

    def _get_quantization_comment(self) -> str:
        """Return a header comment describing quantization mode."""
        if self.quantization == 'none':
            return 'Quantization: None (float32)'
        elif self.quantization == 'int8':
            return 'Quantization: INT8 symmetric (75% weight memory reduction)'
        elif self.quantization == 'int16':
            return 'Quantization: INT16 symmetric (50% weight memory reduction)'
        elif self.quantization == 'float16':
            return 'Quantization: FLOAT16 (reduced precision)'
        return f'Quantization: {self.quantization}'

    def generate_header(self) -> str:
        """Generate common header file content."""
        header = f"""/*
 * Human Activity Recognition Model
 * Generated by HAR Edge Framework
 * Model Type: {self.model_type}
 * Features: {len(self.feature_names)}
 * Classes: {len(self.classes)}
 * Platform: {self.platform}
 * Optimization: {self.optimization.title()}
 * {self._get_optimization_comment()}
 * {self._get_quantization_comment()}
 */

#ifndef HAR_MODEL_H
#define HAR_MODEL_H

{self._get_platform_includes()}
{self._get_quantization_includes()}

// Model configuration
#define NUM_FEATURES {len(self.feature_names)}
#define NUM_CLASSES {len(self.classes)}
#define N_CHANNELS  6
#define SAMPLING_RATE {self.sampling_rate}
#define WINDOW_SIZE {self.window_size}

// Quantization mode
#define QUANTIZATION_MODE "{self.quantization}"
#define QUANTIZATION_ENABLED {1 if self.quantization != 'none' else 0}

// Confidence threshold — prediction returns -1 when below this
#define CONFIDENCE_THRESHOLD {self.confidence_threshold:.2f}f

{self._get_model_specific_declarations()}

// Optimization settings
#define FEATURE_PRECISION {self.feature_precision}
#define DEBUG_ENABLED {1 if self.debug_enabled else 0}
#define BUFFER_OPTIMIZATION {1 if self.buffer_optimization else 0}

{self._get_logging_macros()}

// Activity classes
{self._get_enum_or_define_classes()}

// Function declarations
{self._get_function_declarations()}
{self._generate_iir_filter_declarations()}
#endif // HAR_MODEL_H
"""
        return header.strip()

    def generate_implementation(self, header_filename: str = None) -> str:
        """Generate implementation file content with correct header include."""

        # Extract just the filename from the full path if provided
        if header_filename:
            # Get just the filename part (no path) for the #include
            import os
            header_include = os.path.basename(header_filename)
        else:
            # Fallback to generic name
            header_include = "har_model.h"

        implementation = f"""/*
 * Human Activity Recognition Model Implementation
 * Generated by HAR Edge Framework
 * Model Type: {self.model_type}
 * Trained Features: {len(self.feature_names)}
 * Platform: {self.platform}
 */

#include "{header_include}"
{self._get_impl_includes()}

// Forward declaration of internal prediction function
// Writes per-class probabilities into probs_out[] for confidence computation
int har_predict_internal(float features[NUM_FEATURES], float probs_out[NUM_CLASSES]);

// Activity class names
const char* activity_names[NUM_CLASSES] = {{
    {', '.join([f'"{cls}"' for cls in self.classes])}
}};

{self._generate_iir_filter_implementation()}
{self._generate_feature_scaling_arrays()}

{self._generate_model_specific_implementation()}

void har_init() {{
    // Lightweight initialization function
    // Model is ready to use after this call
    // No Serial output here to avoid dependency issues
}}

// Safe prediction wrapper with input validation and feature scaling
// Returns predicted class id, or -1 if confidence is below CONFIDENCE_THRESHOLD.
// If confidence != NULL, the confidence value (0..1) is written to *confidence.
int har_predict(float features[NUM_FEATURES], float* confidence) {{
    // Input validation
    if (features == NULL) {{
        if (confidence) *confidence = 0.0f;
        return -1; // Error: null pointer
    }}

    // Allocate array for scaled features
    float scaled_features[NUM_FEATURES];

    // Apply feature scaling: (x - mean) / std
    for (int i = 0; i < NUM_FEATURES; i++) {{
        // Check for valid feature values
        if (isnan(features[i]) || isinf(features[i])) {{
            features[i] = 0.0f; // Replace invalid values with zero
        }}

        // Apply StandardScaler transformation: (x - mean) / std
        float std = READ_STD(i);
        if (std < 0.0001f) std = 1.0f; // Prevent division by zero
        scaled_features[i] = (features[i] - READ_MEAN(i)) / std;

        // Clamp scaled features to reasonable range (after scaling)
        if (scaled_features[i] < -10.0f) scaled_features[i] = -10.0f;
        if (scaled_features[i] > 10.0f) scaled_features[i] = 10.0f;
    }}

    // Call model-specific prediction function with SCALED features
    // probs_out receives per-class probabilities for confidence computation
    float probs_out[NUM_CLASSES];
    int result = har_predict_internal(scaled_features, probs_out);

    // Confidence = max per-class probability (already normalized by model)
    float conf = 0.0f;
    for (int i = 0; i < NUM_CLASSES; i++) {{
        if (probs_out[i] > conf) conf = probs_out[i];
    }}
    if (confidence) *confidence = conf;

    // Validate prediction result
    if (result < 0 || result >= NUM_CLASSES) {{
        if (confidence) *confidence = 0.0f;
        return -1;
    }}

    // Return -1 (unknown) if confidence is below threshold
    if (conf < CONFIDENCE_THRESHOLD) {{
        return -1;
    }}

    return result;
}}

{self._generate_prediction_function()}

{self._generate_complete_feature_extraction()}

const char* get_activity_name(int class_id) {{
    if (class_id >= 0 && class_id < NUM_CLASSES) {{
        return activity_names[class_id];
    }}
    return "unknown";
}}

{self._generate_utility_functions()}
"""
        return implementation.strip()

    # ------------------------------------------------------------------
    # Platform-aware helpers for header / implementation generation
    # ------------------------------------------------------------------

    def _is_generic_platform(self) -> bool:
        """Return True if platform is a generic (non-Arduino) target."""
        return self.platform in ('generic_c', 'generic_cpp', 'esp_idf', 'zephyr')

    def _get_impl_includes(self) -> str:
        """Additional includes for the .c/.cpp implementation file."""
        if self.platform in ('generic_c',):
            return '#include <math.h>\n#include <stdlib.h>\n#include <stdio.h>'
        elif self.platform in ('generic_cpp',):
            return '#include <cmath>\n#include <cstdlib>\n#include <cstdio>'
        elif self.platform == 'esp_idf':
            return '#include <math.h>\n#include "esp_log.h"'
        else:
            return '#include <math.h>'

    def _get_platform_includes(self) -> str:
        """Return the appropriate #include directives for the target platform."""
        if self.platform in ('generic_c',):
            return (
                '#include <stdint.h>\n'
                '#include <stddef.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#include <float.h>'
            )
        elif self.platform in ('generic_cpp',):
            return (
                '#include <cstdint>\n'
                '#include <cstddef>\n'
                '#include <cmath>\n'
                '#include <cstring>\n'
                '#include <cfloat>'
            )
        elif self.platform == 'esp_idf':
            return (
                '#include <stdint.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#include "esp_log.h"\n'
                '#include "freertos/FreeRTOS.h"\n'
                '#include "freertos/task.h"'
            )
        elif self.platform == 'zephyr':
            return (
                '#include <stdint.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#include <zephyr/kernel.h>\n'
                '#include <zephyr/logging/log.h>'
            )
        elif self.platform == 'arm_cortex_m':
            return (
                '#include <stdint.h>\n'
                '#include <math.h>\n'
                '#include <string.h>\n'
                '#ifdef __ARM_ARCH\n'
                '    #include "arm_math.h"\n'
                '#endif'
            )
        else:
            # Arduino / ESP32 / seeed_xiao / teensy
            return '#include <Arduino.h>'

    def _get_quantization_includes(self) -> str:
        """Return additional #include directives needed for quantization."""
        if self.quantization in ('int8', 'int16'):
            # stdint.h is needed for int8_t / int16_t
            # Most platform includes already pull it in, but be safe
            if self.platform in ('arduino', 'esp32', 'seeed_xiao', 'teensy'):
                return '#include <stdint.h>   // for int8_t/int16_t (quantized weights)'
            # generic_c, generic_cpp, esp_idf, zephyr, arm_cortex_m already include stdint.h
            return '// stdint.h already included above (needed for quantized weights)'
        return ''

    def _get_enum_or_define_classes(self) -> str:
        """Generate activity class constants — enum in C++, #defines in pure C."""
        # Sanitize class names for use as C identifiers
        safe_names = []
        for cls in self.classes:
            safe = cls.upper().replace(' ', '_').replace('-', '_')
            # Strip non-alnum/underscore chars
            safe = ''.join(c for c in safe if c.isalnum() or c == '_')
            if safe and safe[0].isdigit():
                safe = '_' + safe
            safe_names.append(safe)

        if self.platform == 'generic_c':
            # Pure C: use #define constants (no enum class)
            lines = [f'#define ACTIVITY_{name} {i}'
                     for i, name in enumerate(safe_names)]
            return '\n'.join(lines)
        else:
            entries = ', '.join([f'{name} = {i}' for i, name in enumerate(safe_names)])
            return f'enum ActivityClass {{\n    {entries}\n}};'

    def _get_function_declarations(self) -> str:
        """Generate function declarations appropriate for the platform language."""
        if self.platform == 'generic_c':
            return (
                '#ifdef __cplusplus\n'
                'extern "C" {\n'
                '#endif\n\n'
                'void har_init(void);\n'
                'int har_predict(float features[NUM_FEATURES], float* confidence);\n'
                'void extract_features(float sensor_data[][N_CHANNELS], int samples, float features[]);\n'
                'const char* get_activity_name(int class_id);\n\n'
                '#ifdef __cplusplus\n'
                '}\n'
                '#endif'
            )
        else:
            return (
                'void har_init();\n'
                'int har_predict(float features[NUM_FEATURES], float* confidence);\n'
                'void extract_features(float sensor_data[][N_CHANNELS], int samples, float features[]);\n'
                'const char* get_activity_name(int class_id);'
            )

    @staticmethod
    def _float_literal(v: float) -> str:
        """Format a float as a valid C float literal (always includes decimal point)."""
        s = f"{v:.10g}"
        if '.' not in s and 'e' not in s and 'E' not in s:
            s += '.0'
        return s + 'f'

    def _generate_smoothing_variables(self) -> str:
        """Generate majority-voting variables for temporal smoothing."""
        if self.smoothing_window <= 1:
            return ''
        return (
            f'// Temporal smoothing — majority vote over last {self.smoothing_window} predictions\n'
            f'#define SMOOTHING_WINDOW {self.smoothing_window}\n'
            f'int prediction_history[SMOOTHING_WINDOW];\n'
            f'int prediction_head = 0;\n'
            f'int prediction_count = 0;\n'
        )

    def _generate_smoothing_prediction_logic(self) -> str:
        """Generate the prediction logic block — with or without majority voting."""
        indent = '            '
        if self.smoothing_window <= 1:
            # No smoothing — use raw prediction directly
            return (
                f'{indent}if (predicted_class >= 0) {{\n'
                f'{indent}    activity_name = get_activity_name(predicted_class);\n'
                f'{indent}}} else {{\n'
                f'{indent}    activity_name = "unknown";\n'
                f'{indent}}}\n'
            )
        # Majority voting
        return (
            f'{indent}// Store in history and majority-vote\n'
            f'{indent}prediction_history[prediction_head] = predicted_class;\n'
            f'{indent}prediction_head = (prediction_head + 1) % SMOOTHING_WINDOW;\n'
            f'{indent}if (prediction_count < SMOOTHING_WINDOW) prediction_count++;\n'
            f'{indent}\n'
            f'{indent}// Find majority class\n'
            f'{indent}int vote_counts[NUM_CLASSES] = {{0}};\n'
            f'{indent}int unknown_votes = 0;\n'
            f'{indent}for (int v = 0; v < prediction_count; v++) {{\n'
            f'{indent}    int pc = prediction_history[v];\n'
            f'{indent}    if (pc >= 0 && pc < NUM_CLASSES) vote_counts[pc]++;\n'
            f'{indent}    else unknown_votes++;\n'
            f'{indent}}}\n'
            f'{indent}int best_class = -1, best_votes = unknown_votes;\n'
            f'{indent}for (int c = 0; c < NUM_CLASSES; c++) {{\n'
            f'{indent}    if (vote_counts[c] > best_votes) {{\n'
            f'{indent}        best_votes = vote_counts[c];\n'
            f'{indent}        best_class = c;\n'
            f'{indent}    }}\n'
            f'{indent}}}\n'
            f'{indent}if (best_class >= 0) {{\n'
            f'{indent}    activity_name = get_activity_name(best_class);\n'
            f'{indent}}} else {{\n'
            f'{indent}    activity_name = "unknown";\n'
            f'{indent}}}\n'
        )

    def _has_device_filter(self) -> bool:
        """Check if on-device IIR filter should be generated.

        Only enabled when the user explicitly opts in AND
        low-pass filtering was used during training.
        NOTE: Training uses filtfilt (zero-phase) while on-device uses
        lfilter (causal). This creates a subtle parity gap.
        """
        return (self.enable_iir_filter
                and bool(self.preprocessing.get('low_pass_filter')))

    def _compute_iir_coefficients(self):
        """Compute 2nd-order IIR (Butterworth) coefficients for on-device filtering.

        Returns (b0, b1, b2, a1, a2) normalized so a0=1.
        Uses scipy to match training pipeline exactly.
        """
        try:
            from scipy.signal import butter
        except ImportError:
            return None

        cutoff = self.preprocessing.get('lpf_cutoff_hz', 5)
        order = self.preprocessing.get('lpf_order', 2)
        fs = self.sampling_rate

        # Get transfer function coefficients (numerator b, denominator a)
        b, a = butter(order, cutoff, btype='low', fs=fs)
        return b, a

    def _generate_iir_filter_declarations(self) -> str:
        """Generate IIR filter function declaration for the header."""
        if not self._has_device_filter():
            return ''
        return (
            '\n// On-device IIR low-pass filter (matches training preprocessing)\n'
            '#define IIR_FILTER_ENABLED 1\n'
            'void iir_filter_sample(float raw[N_CHANNELS]);\n'
            'void iir_filter_reset(void);\n'
        )

    def _generate_iir_filter_implementation(self) -> str:
        """Generate C++ IIR filter implementation with embedded coefficients."""
        if not self._has_device_filter():
            return ''

        result = self._compute_iir_coefficients()
        if result is None:
            return '// WARNING: scipy not available — IIR filter coefficients not computed\n'

        b, a = result
        order = len(b) - 1  # filter order

        cutoff = self.preprocessing.get('lpf_cutoff_hz', 5)
        prec = self.feature_precision

        lines = [
            f'// IIR Low-pass filter: Butterworth, cutoff={cutoff}Hz, order={order}, fs={self.sampling_rate}Hz',
            f'// Coefficients computed by scipy.signal.butter to match training pipeline',
            f'#define IIR_ORDER {order}',
            '',
            f'static const float iir_b[{len(b)}] = {{{", ".join(self._float_literal(v) for v in b)}}};',
            f'static const float iir_a[{len(a)}] = {{{", ".join(self._float_literal(v) for v in a)}}};',
            '',
            f'// Filter state: delay lines per channel',
            f'static float iir_x_hist[N_CHANNELS][IIR_ORDER] = {{{{0}}}};  // input history',
            f'static float iir_y_hist[N_CHANNELS][IIR_ORDER] = {{{{0}}}};  // output history',
            '',
            'void iir_filter_reset(void) {',
            f'    for (int ch = 0; ch < N_CHANNELS; ch++) {{',
            f'        for (int i = 0; i < IIR_ORDER; i++) {{',
            '            iir_x_hist[ch][i] = 0.0f;',
            '            iir_y_hist[ch][i] = 0.0f;',
            '        }',
            '    }',
            '}',
            '',
            'void iir_filter_sample(float raw[N_CHANNELS]) {',
            '    for (int ch = 0; ch < N_CHANNELS; ch++) {',
            '        float x = raw[ch];',
            '        float y = iir_b[0] * x;',
            f'        for (int i = 1; i <= IIR_ORDER; i++) {{',
            '            y += iir_b[i] * iir_x_hist[ch][i-1];',
            '            y -= iir_a[i] * iir_y_hist[ch][i-1];',
            '        }',
            '        // Shift history',
            f'        for (int i = IIR_ORDER - 1; i > 0; i--) {{',
            '            iir_x_hist[ch][i] = iir_x_hist[ch][i-1];',
            '            iir_y_hist[ch][i] = iir_y_hist[ch][i-1];',
            '        }',
            '        iir_x_hist[ch][0] = x;',
            '        iir_y_hist[ch][0] = y;',
            '        raw[ch] = y;',
            '    }',
            '}',
        ]
        return '\n'.join(lines) + '\n'

    def _get_logging_macros(self) -> str:
        """Generate platform-portable logging macros.
        
        Provides HAR_LOG(fmt, ...) so utility/debug functions compile on all
        platforms without changing the body of the code.
        """
        if self.platform in ('generic_c', 'generic_cpp'):
            return (
                '// Platform-portable logging\n'
                '#include <stdio.h>\n'
                '#define HAR_LOG(fmt, ...) printf(fmt "\\n", ##__VA_ARGS__)\n'
                '#define HAR_LOG_FLOAT(label, val) printf("%s: %f\\n", (label), (double)(val))'
            )
        elif self.platform == 'esp_idf':
            return (
                '// Platform-portable logging\n'
                '#define HAR_LOG(fmt, ...) ESP_LOGI("HAR", fmt, ##__VA_ARGS__)\n'
                '#define HAR_LOG_FLOAT(label, val) ESP_LOGI("HAR", "%s: %f", (label), (double)(val))'
            )
        elif self.platform == 'zephyr':
            return (
                '// Platform-portable logging\n'
                'LOG_MODULE_REGISTER(har, LOG_LEVEL_INF);\n'
                '#define HAR_LOG(fmt, ...) LOG_INF(fmt, ##__VA_ARGS__)\n'
                '#define HAR_LOG_FLOAT(label, val) LOG_INF("%s: " #val, (label))'
            )
        else:
            # Arduino and Arduino-like (ESP32, Seeed XIAO, Teensy, ARM Cortex-M)
            return (
                '// Platform-portable logging (Arduino)\n'
                '#define HAR_LOG(fmt, ...) do { Serial.println(fmt); } while(0)\n'
                '#define HAR_LOG_FLOAT(label, val) do { Serial.print(label); Serial.print(": "); Serial.println(val, 4); } while(0)'
            )

    def _generate_feature_scaling_arrays(self) -> str:
        """Generate feature scaling arrays with real parameters.
        Uses PROGMEM on AVR platforms to store in flash instead of RAM."""
        precision = self.feature_precision
        
        # Use PROGMEM for AVR-based Arduino boards (limited RAM)
        progmem = 'PROGMEM ' if self.platform == 'arduino' else ''
        read_macro = self._needs_progmem_read()

        # Format all feature means
        means_formatted = []
        for i, mean in enumerate(self.feature_means):
            if i % 10 == 0 and i > 0:
                means_formatted.append(f'\n    {mean:.{precision}f}')
            else:
                means_formatted.append(f'{mean:.{precision}f}')
        means_array = ', '.join(means_formatted)

        # Format all feature stds
        stds_formatted = []
        for i, std in enumerate(self.feature_stds):
            if i % 10 == 0 and i > 0:
                stds_formatted.append(f'\n    {std:.{precision}f}')
            else:
                stds_formatted.append(f'{std:.{precision}f}')
        stds_array = ', '.join(stds_formatted)

        code = f"""// Feature scaling parameters (extracted from trained model)
// Precision: {precision} decimal places ({self.optimization} optimization)
const float feature_means[NUM_FEATURES] {progmem}= {{
    {means_array}
}};

const float feature_stds[NUM_FEATURES] {progmem}= {{
    {stds_array}
}};"""

        if read_macro:
            code += """

// Helper to read float from PROGMEM (AVR only)
static inline float pgm_read_float_near_safe(const float* addr) {
    float val;
    memcpy_P(&val, addr, sizeof(float));
    return val;
}
#define READ_MEAN(i) pgm_read_float_near_safe(&feature_means[i])
#define READ_STD(i) pgm_read_float_near_safe(&feature_stds[i])"""
        else:
            code += """

#define READ_MEAN(i) feature_means[i]
#define READ_STD(i) feature_stds[i]"""

        return code

    def _needs_progmem_read(self) -> bool:
        """Check if platform needs PROGMEM read macros (AVR only)."""
        return self.platform == 'arduino'

    def _generate_complete_feature_extraction(self) -> str:
        """Generate optimization-aware feature extraction function.
        
        CRITICAL: The feature extraction algorithm MUST match training exactly.
        Optimization level affects precision/sampling/window size, NOT the algorithm.
        If the model was trained with orientation-robust features, C++ MUST use
        orientation-robust extraction regardless of optimization level.
        """
        # Detect feature configuration from multiple sources
        orientation_robust = False
        include_per_axis = False
        include_frequency = False
        feature_method = None  # initialise before try blocks to avoid NameError
        
        # Source 1: Explicit feature_config in model_info
        try:
            feature_config = self.model_data.get(
                'model_info', {}).get('feature_config', {})
            if feature_config:
                orientation_robust = feature_config.get(
                    'orientation_robust', False)
                include_per_axis = feature_config.get('include_per_axis', False)
                include_frequency = feature_config.get('include_frequency', False)
        except Exception:
            pass

        # Source 2: Legacy feature_method parameter
        try:
            feature_method = self.model_data.get(
                'model_params', {}).get('feature_method')
            if feature_method in ('orientation_invariant', 'orientation_invariant_time_only'):
                orientation_robust = True
        except Exception:
            pass

        # Source 3: Auto-detect from feature names (most reliable)
        if self.feature_names:
            has_acc_mag = any(str(name).startswith('acc_mag_') for name in self.feature_names)
            has_gyro_mag = any(str(name).startswith('gyro_mag_') for name in self.feature_names)
            has_jerk_mag = any(str(name).startswith('acc_jerk_mag_') for name in self.feature_names)
            if has_acc_mag and has_gyro_mag:
                orientation_robust = True
            # Auto-detect frequency features from names
            freq_suffixes = ('_dominant_frequency', '_spectral_centroid',
                             '_energy_low_freq', '_spectral_rolloff')
            if any(str(name).endswith(freq_suffixes) for name in self.feature_names):
                include_frequency = True
            # Also check for per-axis features
            has_per_axis = any(str(name).startswith(('aX_', 'aY_', 'aZ_', 'gX_', 'gY_', 'gZ_')) 
                             for name in self.feature_names)
            if has_per_axis:
                include_per_axis = True

        # Use orientation-robust features if configured
        if orientation_robust or feature_method == 'orientation_invariant':
            return self._generate_orientation_robust_extraction(include_frequency)

        # Per-axis feature extraction — ALWAYS extracts the same 15 features/axis
        # that match training, regardless of optimization level.
        # Optimization only affects computation method (precision, sorting algorithm)
        # but NEVER changes which features are produced.
        return self._generate_per_axis_extraction()

    # ------------------------------------------------------------------
    # Orientation-robust feature extraction (magnitude-based, 33 features)
    # ------------------------------------------------------------------

    def _generate_orientation_robust_extraction(self, include_frequency=False) -> str:
        """Generate orientation-robust (magnitude-based) feature extraction.

        Produces 33 time-domain features, plus optionally 20 frequency-domain
        features (10 per magnitude) via DFT when include_frequency=True (53 total).
        """
        code = ""

        # DFT helper function (only included when frequency features are needed)
        if include_frequency:
            code += """
// --- DFT-based frequency feature extraction ----------------------------
// Computes 10 frequency features from a magnitude signal via a direct DFT.
// Pipeline: DC removal -> Hann window -> DFT -> feature extraction.
// Matches Python: _fft_with_windowing() + _spectral_statistics().
int extract_frequency_features(float* signal, int samples, float sampling_rate,
                               float* features, int start_idx) {
    int idx = start_idx;
    int half_n = samples / 2;  // positive-frequency bins
    float freq_step = sampling_rate / (float)samples;

    // Precompute 2*PI/N
    float two_pi_over_n = 6.283185307f / (float)samples;

    // --- Step 1: DC removal (subtract mean) ---
    float sig_mean = 0.0f;
    for (int i = 0; i < samples; i++) sig_mean += signal[i];
    sig_mean /= (float)samples;

    // --- Step 2 & 3: Apply Hann window and compute DFT in one pass ---
    // Hann window: w[n] = 0.5 - 0.5 * cos(2*PI*n/(N-1))
    // We apply DC removal + windowing inline during the DFT inner loop
    // to avoid allocating a temporary windowed-signal array.
    float dft_mag[WINDOW_SIZE / 2 + 1];

    float max_mag = 0.0f;
    int max_idx = 0;
    float mag_sum = 0.0f;
    float weighted_freq_sum = 0.0f;

    float pi_over_nm1 = 3.141592654f / (float)(samples - 1);

    for (int k = 1; k <= half_n; k++) {
        float re = 0.0f, im = 0.0f;
        float angle_step = two_pi_over_n * (float)k;
        for (int n = 0; n < samples; n++) {
            // Hann window coefficient: 0.5 - 0.5*cos(2*PI*n/(N-1))
            float w = 0.5f - 0.5f * cosf(2.0f * pi_over_nm1 * (float)n);
            float val = (signal[n] - sig_mean) * w;  // DC-removed + windowed
            float angle = angle_step * (float)n;
            re += val * cosf(angle);
            im -= val * sinf(angle);
        }
        float mag = sqrtf(re * re + im * im);
        dft_mag[k - 1] = mag;

        float freq = (float)k * freq_step;
        if (mag > max_mag) {
            max_mag = mag;
            max_idx = k - 1;
        }
        mag_sum += mag;
        weighted_freq_sum += freq * mag;
    }

    // 0: Dominant frequency (Hz)
    features[idx++] = (float)(max_idx + 1) * freq_step;
    // 1: Dominant frequency magnitude
    features[idx++] = max_mag;
    // 2: Spectral centroid
    features[idx++] = (mag_sum > 0) ? (weighted_freq_sum / mag_sum) : 0.0f;

    // Energy in frequency bands: 0-2 Hz, 2-5 Hz, 5+ Hz
    float energy_low = 0.0f, energy_mid = 0.0f, energy_high = 0.0f;
    for (int k = 0; k < half_n; k++) {
        float freq = (float)(k + 1) * freq_step;
        float e = dft_mag[k] * dft_mag[k];
        if (freq < 2.0f)            energy_low  += e;
        else if (freq < 5.0f)       energy_mid  += e;
        else                         energy_high += e;
    }
    // 3-5: Band energies
    features[idx++] = energy_low;
    features[idx++] = energy_mid;
    features[idx++] = energy_high;

    // 6: Spectral rolloff (freq below which 85% of total magnitude)
    float rolloff_threshold = 0.85f * mag_sum;
    float cumsum = 0.0f;
    float rolloff_freq = (float)half_n * freq_step;
    for (int k = 0; k < half_n; k++) {
        cumsum += dft_mag[k];
        if (cumsum >= rolloff_threshold) {
            rolloff_freq = (float)(k + 1) * freq_step;
            break;
        }
    }
    features[idx++] = rolloff_freq;

    // 7-9: Spectral shape descriptors (EI-style: RMS, skewness, kurtosis of bins)
    // These match Python _spectral_statistics()
    float sq_sum = 0.0f;
    for (int k = 0; k < half_n; k++) sq_sum += dft_mag[k] * dft_mag[k];
    float spec_rms = sqrtf(sq_sum / (float)half_n);

    float spec_mean = mag_sum / (float)half_n;
    float spec_var = (sq_sum / (float)half_n) - (spec_mean * spec_mean);
    float spec_std = sqrtf(spec_var > 0.0f ? spec_var : 0.0001f);

    float m3 = 0.0f, m4 = 0.0f;
    for (int k = 0; k < half_n; k++) {
        float z = (dft_mag[k] - spec_mean) / (spec_std + 1e-7f);
        float z2 = z * z;
        m3 += z2 * z;
        m4 += z2 * z2;
    }
    int nn = half_n;
    // Bias-corrected skewness/kurtosis (pandas convention)
    float spec_skew = 0.0f, spec_kurt = 0.0f;
    if (nn > 2) {
        spec_skew = (m3 / (float)nn) * ((float)nn * (float)(nn + 1))
                    / ((float)(nn - 1) * (float)(nn - 2));
    }
    if (nn > 3) {
        float raw_kurt = m4 / (float)nn;
        spec_kurt = ((float)(nn + 1) * raw_kurt
                     - 3.0f * (float)(nn - 1))
                    * (float)(nn - 1)
                    / ((float)(nn - 2) * (float)(nn - 3))
                    + 3.0f;
        spec_kurt -= 3.0f;  // excess kurtosis (Fisher)
    }

    features[idx++] = spec_rms;
    features[idx++] = spec_skew;
    features[idx++] = spec_kurt;

    return idx;
}

"""

        code += """// Forward declaration for helper function
int extract_magnitude_stats(float* mag, int samples, float* features, int start_idx);

void extract_features(float sensor_data[][N_CHANNELS], int samples, float features[]) {
    // Orientation-robust features (magnitude-based)
    // Time-domain: 15 stats x 2 magnitudes + 3 jerk = 33 features
"""
        if include_frequency:
            code += "    // Frequency-domain: 10 features x 2 magnitudes = 20 features (total: 53)\n"

        code += """
    if (samples <= 1) {
        for (int i = 0; i < NUM_FEATURES; i++) features[i] = 0.0f;
        return;
    }

    // Temporary arrays for magnitude values
    float acc_mag[WINDOW_SIZE];
    float gyro_mag[WINDOW_SIZE];
    float jerk_mag[WINDOW_SIZE];

    // --- Per-window mean centering ---
    // Removes gravity (accel) and orientation-dependent DC bias (gyro)
    // so magnitudes capture only dynamic variation.
    float ax_mean = 0.0f, ay_mean = 0.0f, az_mean = 0.0f;
    float gx_mean = 0.0f, gy_mean = 0.0f, gz_mean = 0.0f;
    for (int i = 0; i < samples; i++) {
        ax_mean += sensor_data[i][0];
        ay_mean += sensor_data[i][1];
        az_mean += sensor_data[i][2];
        gx_mean += sensor_data[i][3];
        gy_mean += sensor_data[i][4];
        gz_mean += sensor_data[i][5];
    }
    ax_mean /= (float)samples; ay_mean /= (float)samples; az_mean /= (float)samples;
    gx_mean /= (float)samples; gy_mean /= (float)samples; gz_mean /= (float)samples;

    // Calculate centered magnitude vectors
    float prev_ax = sensor_data[0][0];
    float prev_ay = sensor_data[0][1];
    float prev_az = sensor_data[0][2];

    for (int i = 0; i < samples; i++) {
        float ax = sensor_data[i][0];
        float ay = sensor_data[i][1];
        float az = sensor_data[i][2];
        float gx = sensor_data[i][3];
        float gy = sensor_data[i][4];
        float gz = sensor_data[i][5];

        // Centered magnitudes (gravity/bias removed)
        float cax = ax - ax_mean, cay = ay - ay_mean, caz = az - az_mean;
        float cgx = gx - gx_mean, cgy = gy - gy_mean, cgz = gz - gz_mean;
        acc_mag[i] = sqrtf(cax*cax + cay*cay + caz*caz);
        gyro_mag[i] = sqrtf(cgx*cgx + cgy*cgy + cgz*cgz);

        // Jerk uses raw (uncentered) differences — centering cancels out in diff
        if (i > 0) {
            float dax = ax - prev_ax;
            float day = ay - prev_ay;
            float daz = az - prev_az;
            jerk_mag[i-1] = sqrtf(dax*dax + day*day + daz*daz);
        }

        prev_ax = ax; prev_ay = ay; prev_az = az;
    }

    int n_jerk = samples - 1;
    int idx = 0;

    // Extract 15 features from acc_mag
    idx = extract_magnitude_stats(acc_mag, samples, features, idx);

    // Extract 15 features from gyro_mag
    idx = extract_magnitude_stats(gyro_mag, samples, features, idx);

    // Extract 3 jerk magnitude features (mean, std, max)
    float jerk_sum = 0.0f, jerk_sum_sq = 0.0f, jerk_max = -1e9f;
    for (int i = 0; i < n_jerk; i++) {
        jerk_sum += jerk_mag[i];
        jerk_sum_sq += jerk_mag[i] * jerk_mag[i];
        if (jerk_mag[i] > jerk_max) jerk_max = jerk_mag[i];
    }

    float jerk_mean = (n_jerk > 0) ? (jerk_sum / n_jerk) : 0.0f;
    float jerk_var = (n_jerk > 0) ? ((jerk_sum_sq / n_jerk) - jerk_mean * jerk_mean) : 0.0f;
    float jerk_std = sqrtf(jerk_var > 0 ? jerk_var : 0.0f);

    features[idx++] = jerk_mean;
    features[idx++] = jerk_std;
    features[idx++] = jerk_max;
"""
        # Insert frequency feature extraction after jerk features
        if include_frequency:
            code += """
    // Extract 7 frequency features from acc_mag via DFT
    idx = extract_frequency_features(acc_mag, samples, (float)SAMPLING_RATE, features, idx);

    // Extract 7 frequency features from gyro_mag via DFT
    idx = extract_frequency_features(gyro_mag, samples, (float)SAMPLING_RATE, features, idx);
"""

        code += """
    // Fill remaining features with zeros
    for (; idx < NUM_FEATURES; idx++) features[idx] = 0.0f;
}

// Helper function to extract statistical features from magnitude vector
int extract_magnitude_stats(float* mag, int samples, float* features, int start_idx) {
    int idx = start_idx;
    float n = (float)samples;

    // First pass: sum, sum_sq, min, max
    float sum = 0.0f, sum_sq = 0.0f;
    float min_val = 1e9f, max_val = -1e9f;
    for (int i = 0; i < samples; i++) {
        sum += mag[i];
        sum_sq += mag[i] * mag[i];
        if (mag[i] < min_val) min_val = mag[i];
        if (mag[i] > max_val) max_val = mag[i];
    }

    float mean = sum / n;
    float variance = (sum_sq / n) - (mean * mean);
    float std = sqrtf(variance > 0 ? variance : 0.0f);
    float rms = sqrtf(sum_sq / n);
    float energy = sum_sq;
    float range = max_val - min_val;

    features[idx++] = mean;         // 0: mean
    features[idx++] = std;          // 1: std
    features[idx++] = min_val;      // 2: min
    features[idx++] = max_val;      // 3: max
    features[idx++] = range;        // 4: range

    // Median and quartiles (requires sorting a copy)
    float sorted[WINDOW_SIZE];
    for (int i = 0; i < samples; i++) sorted[i] = mag[i];

    // Insertion sort
    for (int i = 1; i < samples; i++) {
        float key = sorted[i];
        int j = i - 1;
        while (j >= 0 && sorted[j] > key) {
            sorted[j + 1] = sorted[j];
            j--;
        }
        sorted[j + 1] = key;
    }

    float median = (samples % 2 == 0) ?
        (sorted[samples/2 - 1] + sorted[samples/2]) / 2.0f :
        sorted[samples/2];
    // Quartiles using linear interpolation (matches numpy default)
    float q25_pos = 0.25f * (samples - 1);
    int q25_lo = (int)q25_pos;
    float q25_frac = q25_pos - q25_lo;
    float q25 = sorted[q25_lo] + q25_frac * (sorted[q25_lo + 1 < samples ? q25_lo + 1 : q25_lo] - sorted[q25_lo]);

    float q75_pos = 0.75f * (samples - 1);
    int q75_lo = (int)q75_pos;
    float q75_frac = q75_pos - q75_lo;
    float q75 = sorted[q75_lo] + q75_frac * (sorted[q75_lo + 1 < samples ? q75_lo + 1 : q75_lo] - sorted[q75_lo]);

    float iqr = q75 - q25;

    features[idx++] = median;       // 5: median
    features[idx++] = q25;          // 6: q25
    features[idx++] = q75;          // 7: q75
    features[idx++] = iqr;          // 8: iqr

    // Skewness and kurtosis - bias-corrected (pandas/scipy formula)
    // Use population std for z-scores to match pandas computation exactly
    float pop_std = sqrtf(variance > 0.0f ? variance : 0.0001f);

    float m3_sum = 0.0f, m4_sum = 0.0f;
    for (int i = 0; i < samples; i++) {
        float z = (mag[i] - mean) / (pop_std + 1e-7f);
        float z2 = z * z;
        m3_sum += z * z2;
        m4_sum += z2 * z2;
    }

    float g1 = m3_sum / n;
    float skewness = 0.0f;
    if (samples >= 3) {
        skewness = sqrtf(n * (n - 1.0f)) / (n - 2.0f) * g1;
    }

    float g2 = m4_sum / n - 3.0f;
    float kurtosis = -3.0f;
    if (samples >= 4) {
        kurtosis = (n - 1.0f) / ((n - 2.0f) * (n - 3.0f)) * ((n + 1.0f) * g2 + 6.0f);
    }

    features[idx++] = skewness;     // 9: skewness
    features[idx++] = kurtosis;     // 10: kurtosis
    features[idx++] = rms;          // 11: rms
    features[idx++] = energy;       // 12: energy

    // Zero crossings and mean crossing rate
    int zero_crossings = 0;
    int mean_crossings = 0;
    for (int i = 1; i < samples; i++) {
        if ((mag[i-1] * mag[i]) < 0) zero_crossings++;
        if ((mag[i-1] - mean) * (mag[i] - mean) < 0) mean_crossings++;
    }

    features[idx++] = (float)zero_crossings;       // 13: zero_crossings
    features[idx++] = (float)mean_crossings / n;   // 14: mean_crossing_rate

    return idx;
}
"""
        return code

    # ------------------------------------------------------------------
    # Per-axis feature extraction (15 features × 6 axes = 90 features)
    # ------------------------------------------------------------------

    def _generate_per_axis_extraction(self) -> str:
        """Generate per-axis feature extraction that ALWAYS matches training.
        
        CRITICAL: All optimization levels produce the SAME 15 features per axis
        in the SAME order. The optimization level only affects:
          - Sorting algorithm (insertion sort vs bubble sort)
          - Floating-point precision (float vs double accumulation)
          - Input validation strictness
        It NEVER changes which features are extracted.
        """
        # Use double-precision accumulation for accuracy mode
        use_double = self.optimization == 'accuracy'
        acc_type = 'double' if use_double else 'float'

        return f"""void extract_features(float sensor_data[][N_CHANNELS], int samples, float features[]) {{
    // Per-axis feature extraction — 15 features per axis × 6 axes = 90 features
    // MUST match training feature extraction exactly regardless of optimization level.
    // Optimization: {self.optimization.upper()} ({'double-precision' if use_double else 'single-precision'} accumulation)

    // Input validation
    if (samples <= 1 || samples > WINDOW_SIZE) {{
        for (int i = 0; i < NUM_FEATURES; i++) features[i] = 0.0f;
        return;
    }}

    int feature_idx = 0;

    // For each sensor axis (aX, aY, aZ, gX, gY, gZ)
    for (int axis = 0; axis < 6; axis++) {{
        // Copy data for sorting (used for median and quartiles)
        float sorted_data[WINDOW_SIZE];
        for (int i = 0; i < samples; i++) {{
            sorted_data[i] = sensor_data[i][axis];
        }}

        // Insertion sort — O(n²) worst case but fast for small/partially-sorted arrays
        for (int i = 1; i < samples; i++) {{
            float key = sorted_data[i];
            int j = i - 1;
            while (j >= 0 && sorted_data[j] > key) {{
                sorted_data[j + 1] = sorted_data[j];
                j--;
            }}
            sorted_data[j + 1] = key;
        }}

        // Statistical calculations
        {acc_type} sum = 0, sum_sq = 0;
        float min_val = sensor_data[0][axis];
        float max_val = sensor_data[0][axis];

        for (int i = 0; i < samples; i++) {{
            {acc_type} val = ({acc_type})sensor_data[i][axis];
            sum += val;
            sum_sq += val * val;
            if (sensor_data[i][axis] < min_val) min_val = sensor_data[i][axis];
            if (sensor_data[i][axis] > max_val) max_val = sensor_data[i][axis];
        }}

        float n = (float)samples;
        float mean = (float)(sum / n);
        float variance = (float)((sum_sq / n) - (({acc_type})mean * ({acc_type})mean));
        if (variance < 0.0f) variance = 0.0f;
        float std_dev = sqrtf(variance);

        // Median and quartiles from sorted data
        int mid = samples / 2;
        float median = (samples % 2 == 0)
            ? (sorted_data[mid - 1] + sorted_data[mid]) / 2.0f
            : sorted_data[mid];
        // Quartiles using linear interpolation (matches numpy default)
        float q25_pos = 0.25f * (samples - 1);
        int q25_lo = (int)q25_pos;
        float q25_frac = q25_pos - q25_lo;
        float q25 = sorted_data[q25_lo] + q25_frac * (sorted_data[q25_lo + 1 < samples ? q25_lo + 1 : q25_lo] - sorted_data[q25_lo]);

        float q75_pos = 0.75f * (samples - 1);
        int q75_lo = (int)q75_pos;
        float q75_frac = q75_pos - q75_lo;
        float q75 = sorted_data[q75_lo] + q75_frac * (sorted_data[q75_lo + 1 < samples ? q75_lo + 1 : q75_lo] - sorted_data[q75_lo]);

        float iqr = q75 - q25;

        // Feature vector (same 15 features in same order as training)
        features[feature_idx++] = mean;                          // 0: mean
        features[feature_idx++] = std_dev;                       // 1: std
        features[feature_idx++] = min_val;                       // 2: min
        features[feature_idx++] = max_val;                       // 3: max
        features[feature_idx++] = max_val - min_val;             // 4: range
        features[feature_idx++] = median;                        // 5: median
        features[feature_idx++] = q25;                           // 6: q25
        features[feature_idx++] = q75;                           // 7: q75
        features[feature_idx++] = iqr;                           // 8: iqr

        // Skewness and kurtosis — bias-corrected (pandas/scipy formula)
        // Use population std for z-scores to match pandas computation exactly
        float pop_std = sqrtf(variance > 0.0f ? variance : 0.0001f);

        float m3_sum = 0.0f, m4_sum = 0.0f;
        for (int i = 0; i < samples; i++) {{
            float z = (sensor_data[i][axis] - mean) / (pop_std + 1e-7f);
            float z2 = z * z;
            m3_sum += z * z2;
            m4_sum += z2 * z2;
        }}

        // Skewness with bias correction
        float g1 = m3_sum / n;
        float skewness = 0.0f;
        if (samples >= 3) {{
            skewness = sqrtf(n * (n - 1.0f)) / (n - 2.0f) * g1;
        }}

        // Excess kurtosis with bias correction
        float g2 = m4_sum / n - 3.0f;
        float kurtosis = -3.0f;
        if (samples >= 4) {{
            kurtosis = (n - 1.0f) / ((n - 2.0f) * (n - 3.0f)) * ((n + 1.0f) * g2 + 6.0f);
        }}

        features[feature_idx++] = skewness;                     // 9: skewness
        features[feature_idx++] = kurtosis;                      // 10: kurtosis
        features[feature_idx++] = sqrtf((float)(sum_sq / n));    // 11: rms
        features[feature_idx++] = (float)sum_sq;                 // 12: energy

        // Zero-crossings (signal crosses zero)
        int zero_crossings = 0;
        for (int i = 1; i < samples; i++) {{
            if (sensor_data[i-1][axis] * sensor_data[i][axis] < 0)
                zero_crossings++;
        }}
        features[feature_idx++] = (float)zero_crossings;        // 13: zero_crossings

        // Mean-crossing rate (normalised)
        int mean_crossings = 0;
        for (int i = 1; i < samples; i++) {{
            if ((sensor_data[i-1][axis] - mean) * (sensor_data[i][axis] - mean) < 0)
                mean_crossings++;
        }}
        features[feature_idx++] = (float)mean_crossings / n;    // 14: mean_crossing_rate
    }}

    // Total: 15 features/axis × 6 axes = 90 time-domain features
    // Fill any remaining slots (should be zero if calculation is correct)
    while (feature_idx < NUM_FEATURES) {{
        features[feature_idx++] = 0.0f;
    }}
}}"""

    @abstractmethod
    def _get_model_specific_declarations(self) -> str:
        """Generate model-specific declarations for header file."""
        pass

    @abstractmethod
    def _generate_model_specific_implementation(self) -> str:
        """Generate model-specific implementation code."""
        pass

    @abstractmethod
    def _generate_prediction_function(self) -> str:
        """Generate model-specific prediction function."""
        pass

    @abstractmethod
    def _generate_utility_functions(self) -> str:
        """Generate model-specific utility functions."""
        pass

    def generate_example_sketch(self, header_filename: str = None) -> str:
        """Generate platform-appropriate example code."""

        # Extract just the filename from the full path if provided
        if header_filename:
            import os
            header_include = os.path.basename(header_filename)
        else:
            header_include = "har_model.h"

        # Dispatch to platform-specific example generators
        if self.platform in ('generic_c', 'generic_cpp'):
            return self._generate_generic_example(header_include)
        elif self.platform == 'esp_idf':
            return self._generate_esp_idf_example(header_include)
        else:
            return self._generate_arduino_example(header_include)

    def _generate_generic_example(self, header_include: str) -> str:
        """Generate a portable C/C++ main() example (no Arduino dependency)."""
        is_cpp = self.platform == 'generic_cpp'
        ext = 'cpp' if is_cpp else 'c'
        io_include = '<cstdio>' if is_cpp else '<stdio.h>'
        math_include = '<cmath>' if is_cpp else '<math.h>'
        stdlib_include = '<cstdlib>' if is_cpp else '<stdlib.h>'

        return f"""/*
 * HAR Model — Portable {('C++' if is_cpp else 'C')} Example
 * Model Type: {self.model_type}
 * Optimization: {self.optimization.upper()}
 *
 * Compile:
 *   {'g++' if is_cpp else 'gcc'} -O2 -o har_example example.{ext} har_model.{ext} -lm
 *
 * This file demonstrates how to call the generated HAR model from
 * a plain {('C++' if is_cpp else 'C')} program.  Replace the dummy sensor data
 * with your actual sensor reading code.
 */

#include "{header_include}"
#include {io_include}
#include {math_include}
#include {stdlib_include}

/* ------------------------------------------------------------------ */
/*  Provide your sensor data here                                      */
/* ------------------------------------------------------------------ */

/**
 * Fill sensor_data[WINDOW_SIZE][N_CHANNELS] with one window of IMU readings.
 * Columns: aX, aY, aZ (m/s²), gX, gY, gZ (deg/s or rad/s)
 * Return 0 on success, non-zero on error.
 */
static int read_sensor_window(float sensor_data[][N_CHANNELS]) {{
    /* --- REPLACE with actual sensor/file reading code --- */
    for (int i = 0; i < WINDOW_SIZE; i++) {{
        sensor_data[i][0] = 0.0f;   /* aX */
        sensor_data[i][1] = 0.0f;   /* aY */
        sensor_data[i][2] = 9.81f;  /* aZ (gravity) */
        sensor_data[i][3] = 0.0f;   /* gX */
        sensor_data[i][4] = 0.0f;   /* gY */
        sensor_data[i][5] = 0.0f;   /* gZ */
    }}
    return 0;
}}

/* ------------------------------------------------------------------ */

int main({"void" if not is_cpp else ""}) {{
    printf("HAR Model — {self.model_type.upper()} ({self.optimization.title()})\\n");
    printf("Features: %d | Classes: %d | Window: %d samples @ %d Hz\\n",
           NUM_FEATURES, NUM_CLASSES, WINDOW_SIZE, SAMPLING_RATE);

    har_init();

    float sensor_data[WINDOW_SIZE][N_CHANNELS];
    float features[NUM_FEATURES];

    /* Main inference loop — run until interrupted */
    int iteration = 0;
    while (iteration < 10) {{  /* Change to 'while(1)' for continuous operation */
        if (read_sensor_window(sensor_data) != 0) {{
            printf("Error reading sensor data\\n");
            return 1;
        }}

        extract_features(sensor_data, WINDOW_SIZE, features);

        int predicted_class = har_predict(features, NULL);
        const char* activity = get_activity_name(predicted_class);

        printf("[%04d] Predicted: %s (class %d)\\n",
               iteration, activity, predicted_class);
        iteration++;
    }}

    printf("Done.\\n");
    return 0;
}}
"""

    def _generate_esp_idf_example(self, header_include: str) -> str:
        """Generate an ESP-IDF app_main() example."""
        return f"""/*
 * HAR Model — ESP-IDF Example
 * Model Type: {self.model_type}
 * Optimization: {self.optimization.upper()}
 *
 * Place in main/main.c of your ESP-IDF project.
 * Build: idf.py build
 * Flash: idf.py flash monitor
 */

#include "{header_include}"
#include <stdio.h>
#include <math.h>
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2c.h"

static const char* TAG = "HAR";

/* ------------------------------------------------------------------ */
/*  Replace with your sensor driver                                    */
/* ------------------------------------------------------------------ */
static int read_sensor_window(float sensor_data[][N_CHANNELS]) {{
    /* TODO: Read {self.window_size} samples from IMU via I2C/SPI */
    for (int i = 0; i < WINDOW_SIZE; i++) {{
        sensor_data[i][0] = 0.0f;
        sensor_data[i][1] = 0.0f;
        sensor_data[i][2] = 9.81f;
        sensor_data[i][3] = 0.0f;
        sensor_data[i][4] = 0.0f;
        sensor_data[i][5] = 0.0f;
    }}
    return 0;
}}

void app_main(void) {{
    ESP_LOGI(TAG, "HAR Model — {self.model_type.upper()} ({self.optimization.title()})");
    ESP_LOGI(TAG, "Features: %d | Classes: %d | Window: %d @ %d Hz",
             NUM_FEATURES, NUM_CLASSES, WINDOW_SIZE, SAMPLING_RATE);

    har_init();

    float sensor_data[WINDOW_SIZE][N_CHANNELS];
    float features[NUM_FEATURES];

    while (1) {{
        if (read_sensor_window(sensor_data) != 0) {{
            ESP_LOGE(TAG, "Sensor read error");
            vTaskDelay(pdMS_TO_TICKS(1000));
            continue;
        }}

        extract_features(sensor_data, WINDOW_SIZE, features);
        int predicted_class = har_predict(features, NULL);
        const char* activity = get_activity_name(predicted_class);

        ESP_LOGI(TAG, "Predicted: %s (class %d)", activity, predicted_class);

        vTaskDelay(pdMS_TO_TICKS({int(1000 * self.window_size / self.sampling_rate)}));
    }}
}}
"""

    def _generate_arduino_example(self, header_include: str) -> str:
        """Generate optimization-aware Arduino sketch with correct header include."""

        header_include = header_include or "har_model.h"

        # Optimization-specific delay and settings
        delay_ms = {
            'speed': 5,      # Fast sampling for speed optimization
            'power': 50,     # Slower sampling for power efficiency
            'accuracy': 10,  # Moderate sampling for accuracy
            'balanced': 10   # Standard sampling
        }.get(self.optimization, 10)

        # Platform-specific IMU initialization code
        platform_code = self._get_platform_specific_code()

        sketch_code = f"""/*
 * HAR Model Example Sketch
 * Demonstrates usage of the generated HAR model
 * Model Type: {self.model_type}
 * Optimization: {self.optimization.upper()}
 * {self._get_optimization_comment()}
 */

#include "{header_include}"

{platform_code['includes']}

{platform_code['defines']}

// Data collection variables
float sensor_buffer[WINDOW_SIZE][N_CHANNELS];  // aX, aY, aZ, gX, gY, gZ
int buffer_index = 0;
float features[NUM_FEATURES];
unsigned long last_reading = 0;
const unsigned long READING_INTERVAL = 1000 / SAMPLING_RATE; // ms between readings

{platform_code['overlap_defines']}

{self._generate_smoothing_variables()}

void setup() {{
    Serial.begin(115200);
    while (!Serial)
        delay(10);

    // Print optimization info
    Serial.println("HAR Model - {self.optimization.title()} Optimization");
    Serial.println("========================================");
    Serial.println("Configuration:");
    Serial.print("  Sampling Rate: ");
    Serial.print(SAMPLING_RATE);
    Serial.println(" Hz");
    Serial.print("  Window Size: ");
    Serial.print(WINDOW_SIZE);
    Serial.println(" samples");
    Serial.print("  Features: ");
    Serial.println(NUM_FEATURES);
    Serial.print("  Optimization: ");
    Serial.println("{self.optimization.title()}");

    // Initialize HAR model
    har_init();
    #ifdef IIR_FILTER_ENABLED
    iir_filter_reset();
    #endif

{platform_code['imu_init']}

    Serial.println("HAR Model Ready!");
    Serial.println("Collecting sensor data...");
}}

void loop() {{
    unsigned long current_time = millis();

    // Check if it's time for a new reading
    if (current_time - last_reading >= READING_INTERVAL) {{
        last_reading = current_time;

{platform_code['sensor_read']}

        // Apply on-device IIR filter (matches training preprocessing)
        #ifdef IIR_FILTER_ENABLED
        {{
            float raw_sample[N_CHANNELS] = {{aX, aY, aZ, gX, gY, gZ}};
            iir_filter_sample(raw_sample);
            aX = raw_sample[0]; aY = raw_sample[1]; aZ = raw_sample[2];
            gX = raw_sample[3]; gY = raw_sample[4]; gZ = raw_sample[5];
        }}
        #endif

        // Store in buffer
        sensor_buffer[buffer_index][0] = aX;
        sensor_buffer[buffer_index][1] = aY;
        sensor_buffer[buffer_index][2] = aZ;
        sensor_buffer[buffer_index][3] = gX;
        sensor_buffer[buffer_index][4] = gY;
        sensor_buffer[buffer_index][5] = gZ;

        buffer_index++;

        // Check if buffer is full → run inference
        const char* activity_name = NULL;
        if (buffer_index >= WINDOW_SIZE) {{
            // Extract features and predict BEFORE overlap copy
            extract_features(sensor_buffer, WINDOW_SIZE, features);
            float confidence = 0.0f;
            int predicted_class = har_predict(features, &confidence);

{self._generate_smoothing_prediction_logic()}

            // Shift buffer for overlap: keep the last overlap portion
            int keep_samples = WINDOW_SIZE - (int)buffer_index_shift;
            for (int i = 0; i < keep_samples; i++) {{
                for (int axis = 0; axis < N_CHANNELS; axis++) {{
                    sensor_buffer[i][axis] = sensor_buffer[i + (int)buffer_index_shift][axis];
                }}
            }}
            buffer_index = keep_samples;
        }}

        // Always output sensor CSV (for Device Test graph plotting)
        // Append prediction only on inference cycles
        Serial.print(aX, 4); Serial.print(",");
        Serial.print(aY, 4); Serial.print(",");
        Serial.print(aZ, 4); Serial.print(",");
        Serial.print(gX, 4); Serial.print(",");
        Serial.print(gY, 4); Serial.print(",");
        Serial.print(gZ, 4);
        if (activity_name != NULL) {{
            Serial.print(",");
            Serial.print(activity_name);
        }}
        Serial.println();
    }}

    delay({delay_ms});  // Optimization-specific delay
}}"""

        return sketch_code

    def _get_platform_specific_code(self) -> dict:
        """Get platform-specific code snippets for IMU initialization and sensor reading."""

        if self.platform == 'seeed_xiao':
            return {
                'includes': """#include <LSM6DS3.h>
#include <Wire.h>

//Create a instance of class LSM6DS3
LSM6DS3 myIMU(I2C_MODE, 0x6A);  //I2C device address 0x6A""",
                'defines': """/* Constant defines -------------------------------------------------------- */
#define CONVERT_G_TO_MS2 9.80665f
#define MAX_ACCEPTED_RANGE 2.0f  // starting 03/2022, models are generated setting range to +-2, but this example use Arudino library which set range to +-4g. If you are using an older model, ignore this value and use 4.0f instead""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const float buffer_index_shift = WINDOW_SIZE * (1 - OVERLAP);""",
                'imu_init': """    // Initialize I2C bus first
    Wire.begin();
    delay(100);  // Give I2C time to stabilize

    // Initialize IMU sensor
    Serial.println("Initializing IMU sensor...");

    // LSM6DS3 begin() returns 0 on SUCCESS, non-zero on failure
    if (myIMU.begin() != 0) {
        Serial.println("❌ Failed to initialize IMU!");
        Serial.println("Trying alternate I2C address 0x6B...");

        // Try alternate address
        LSM6DS3 myIMU_alt(I2C_MODE, 0x6B);
        if (myIMU_alt.begin() != 0) {
            Serial.println("❌ IMU not found at 0x6A or 0x6B");
            Serial.println("Check I2C connections and power");
            while (1) {
                delay(100);  // Halt - cannot continue without IMU
            }
        } else {
            Serial.println("✅ IMU found at address 0x6B!");
            // Note: You'll need to update the global myIMU object address
        }
    } else {
        Serial.println("✅ IMU initialized successfully at 0x6A!");
    }

    // Print IMU settings
    Serial.print("Accelerometer range: ±");
    Serial.print(MAX_ACCEPTED_RANGE);
    Serial.println("g");""",
                'sensor_read': """        // Read sensor data from IMU
        float aX = myIMU.readFloatAccelX() * CONVERT_G_TO_MS2;
        float aY = myIMU.readFloatAccelY() * CONVERT_G_TO_MS2;
        float aZ = myIMU.readFloatAccelZ() * CONVERT_G_TO_MS2;
        float gX = myIMU.readFloatGyroX();
        float gY = myIMU.readFloatGyroY();
        float gZ = myIMU.readFloatGyroZ();""",
                'motion_stats': ""
            }

        elif self.platform == 'm5stack':
            # M5StickC Plus2 with built-in IMU via M5Unified
            return {
                'includes': '#include "M5StickCPlus2.h"',
                'defines': """#define CONVERT_G_TO_MS2 9.80665f""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const int buffer_index_shift = (int)(WINDOW_SIZE * (1 - OVERLAP));""",
                'imu_init': """    // Initialize M5StickC Plus2
    auto cfg = M5.config();
    StickCP2.begin(cfg);

    Serial.println("✅ M5StickC Plus2 initialized!");
    StickCP2.Display.setRotation(1);
    StickCP2.Display.setTextColor(GREEN);
    StickCP2.Display.setTextDatum(middle_center);
    StickCP2.Display.setFont(&fonts::FreeSansBold9pt7b);
    StickCP2.Display.setTextSize(1);
    StickCP2.Display.setCursor(0, 40);
    StickCP2.Display.printf("HAR Model Ready\\r\\n");
    StickCP2.Display.printf("Sampling at %d Hz\\r\\n", SAMPLING_RATE);""",
                'sensor_read': """        // Read sensor data from M5StickC Plus2 IMU
        float aX = 0, aY = 0, aZ = 0, gX = 0, gY = 0, gZ = 0;
        if (StickCP2.Imu.update()) {
            auto imu_data = StickCP2.Imu.getImuData();

            // Convert accelerometer from G to m/s²
            aX = imu_data.accel.x * CONVERT_G_TO_MS2;
            aY = imu_data.accel.y * CONVERT_G_TO_MS2;
            aZ = imu_data.accel.z * CONVERT_G_TO_MS2;

            // Gyroscope in degrees/sec
            gX = imu_data.gyro.x;
            gY = imu_data.gyro.y;
            gZ = imu_data.gyro.z;
        }""",
                'motion_stats': ""
            }

        elif self.platform == 'esp32':
            # ESP32 with MPU6050/MPU6886
            return {
                'includes': """#include <Wire.h>
#include "MPU6886.h"  // or MPU6050.h depending on your sensor

MPU6886 IMU;  // Create IMU instance""",
                'defines': """#define CONVERT_G_TO_MS2 9.80665f""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const int buffer_index_shift = (int)(WINDOW_SIZE * (1 - OVERLAP));""",
                'imu_init': """    // Initialize I2C
    Wire.begin();

    // Initialize IMU sensor
    Serial.println("Initializing IMU sensor...");
    if (IMU.Init() != 0) {
        Serial.println("❌ Failed to initialize IMU!");
        while (1) delay(100);
    }
    Serial.println("✅ IMU initialized successfully!");""",
                'sensor_read': """        // Read sensor data
        float aX, aY, aZ, gX, gY, gZ;
        IMU.getAccelData(&aX, &aY, &aZ);
        IMU.getGyroData(&gX, &gY, &gZ);

        // Convert to m/s²
        aX *= CONVERT_G_TO_MS2;
        aY *= CONVERT_G_TO_MS2;
        aZ *= CONVERT_G_TO_MS2;""",
                'motion_stats': ""
            }

        else:  # Generic Arduino
            return {
                'includes': """// Include your IMU library here
// #include <Adafruit_MPU6050.h>
// #include <Adafruit_Sensor.h>
#include <Wire.h>""",
                'defines': """#define CONVERT_G_TO_MS2 9.80665f""",
                'overlap_defines': f"""#define OVERLAP {self.overlap:.2f}  // {int(self.overlap * 100)}% overlap
const int buffer_index_shift = (int)(WINDOW_SIZE * (1 - OVERLAP));""",
                'imu_init': """    // Initialize I2C
    Wire.begin();

    // Initialize IMU sensor
    Serial.println("Initializing IMU sensor...");
    // Add your IMU initialization code here
    Serial.println("✅ IMU initialized!");""",
                'sensor_read': """        // Read sensor data (replace with your IMU library calls)
        float aX = 0.0f;  // Replace with actual accelerometer X
        float aY = 0.0f;  // Replace with actual accelerometer Y
        float aZ = 9.8f;  // Replace with actual accelerometer Z
        float gX = 0.0f;  // Replace with actual gyroscope X
        float gY = 0.0f;  // Replace with actual gyroscope Y
        float gZ = 0.0f;  // Replace with actual gyroscope Z""",
                'motion_stats': ""
            }

    def _set_optimization_parameters(self):
        """Set parameters based on optimization strategy and model complexity.

        CRITICAL: ``window_size`` and ``sampling_rate`` MUST match training.
        Changing them would alter feature distributions and break prediction
        accuracy.  These values are read from model metadata if available;
        otherwise sensible defaults (100 Hz, 150 samples = 1.5 s) are used.
        The optimization level only affects **precision**, **debug output**,
        and **buffer strategy** — never the data acquisition parameters.
        """
        # ----------------------------------------------------------------
        # 1. Read training-time acquisition params from model metadata
        # ----------------------------------------------------------------
        model_params = self.model_data.get('model_params', {})
        model_info = self.model_data.get('model_info', {})
        fe_config = model_info.get('fe_config', {})

        # Prefer fe_config (written by Feature Engineering tab) over model_params
        stored_sampling_rate = (
            fe_config.get('sampling_rate')
            or model_params.get('sampling_rate')
        )
        stored_window_size_ms = (
            fe_config.get('window_size_ms')
            or model_params.get('window_size_ms')
        )

        if stored_sampling_rate and stored_window_size_ms:
            self.sampling_rate = int(stored_sampling_rate)
            self.window_size = int(
                (stored_window_size_ms / 1000) * self.sampling_rate)
        else:
            # Fallback: use standard HAR defaults
            self.sampling_rate = 100
            self.window_size = 150  # 1.5 s @ 100 Hz

        # ----------------------------------------------------------------
        # 2. Set optimization-specific parameters (NEVER touch window/rate)
        # ----------------------------------------------------------------
        complexity_factor = self._calculate_complexity_factor()

        if self.optimization == 'accuracy':
            self.feature_precision = 6
            self.debug_enabled = True
            self.buffer_optimization = False
        elif self.optimization == 'speed':
            self.feature_precision = max(2, min(3, int(4 - complexity_factor)))
            self.debug_enabled = False
            self.buffer_optimization = True
        elif self.optimization == 'power':
            # Min precision of 3 — scaler values are tiny (0.004–0.017)
            # and rounding to 1 decimal makes them 0.0, breaking normalisation
            self.feature_precision = max(3, min(4, int(5 - complexity_factor)))
            self.debug_enabled = False
            self.buffer_optimization = True
        else:  # balanced
            self.feature_precision = 4
            self.debug_enabled = False
            self.buffer_optimization = False

        # Final bounds
        self.sampling_rate = max(10, min(200, self.sampling_rate))
        self.window_size = max(20, min(500, self.window_size))
        self.feature_precision = max(1, min(8, self.feature_precision))

    def _calculate_complexity_factor(self) -> float:
        """
        Calculate model complexity factor based on features, classes, and model type.

        Returns:
            Float representing relative complexity (1.0 = baseline, >1.0 = more complex)
        """
        num_features = len(self.feature_names)
        num_classes = len(self.classes)

        # Base complexity from features and classes
        feature_factor = num_features / 50.0  # Normalize around 50 features
        class_factor = num_classes / 4.0      # Normalize around 4 classes

        # Model-type specific complexity multipliers
        model_multipliers = {
            'neural_network': 1.5,   # Neural networks are more complex
            'random_forest': 1.2,    # Random forests are moderately complex
            'svm': 1.3,              # SVMs can be complex
            'unknown': 1.0           # Default
        }

        model_multiplier = model_multipliers.get(self.model_type, 1.0)

        # Calculate overall complexity
        complexity = (feature_factor + class_factor) * model_multiplier / 2.0

        # Apply reasonable bounds
        return max(0.5, min(5.0, complexity))

    def _get_optimization_comment(self) -> str:
        """Get optimization-specific comment for generated code."""
        optimization_descriptions = {
            'accuracy': 'Optimized for maximum accuracy - higher sampling rate and precision',
            'speed': 'Optimized for fast inference - reduced sampling and simplified calculations',
            'power': 'Optimized for power efficiency - minimal sampling and low-power operations',
            'balanced': 'Balanced optimization - good trade-off between accuracy, speed, and power'
        }
        return optimization_descriptions.get(self.optimization, 'Standard configuration')

    def _validate_model_data(self, model_data: Dict[str, Any]) -> None:
        """
        Validate required model data fields and consistency.

        Args:
            model_data: Dictionary containing model parameters

        Raises:
            ModelDataError: If validation fails
        """
        if not isinstance(model_data, dict):
            raise ModelDataError("model_data must be a dictionary")

        # Check required fields
        required_fields = ['model_type', 'feature_names', 'classes']
        for field in required_fields:
            if field not in model_data:
                raise ModelDataError(f"Missing required field: '{field}'")

            value = model_data[field]
            if value is None:
                raise ModelDataError(f"Field '{field}' cannot be None")

            if field in ['feature_names', 'classes'] and not value:
                raise ModelDataError(f"Field '{field}' cannot be empty")

        # Validate model_type
        valid_model_types = ['random_forest', 'neural_network', 'svm',
                             'pytorch_mlp', 'pytorch_cnn', 'arm_cortex_m']
        if model_data['model_type'] not in valid_model_types:
            raise ModelDataError(f"Invalid model_type: '{model_data['model_type']}'. "
                                 f"Valid types: {valid_model_types}")

        # Validate feature_names
        feature_names = model_data['feature_names']
        if not isinstance(feature_names, list):
            raise ModelDataError("feature_names must be a list")

        if len(feature_names) < 1:
            raise ModelDataError("At least one feature is required")

        if len(feature_names) > 1000:
            raise ModelDataError("Too many features (max 1000 supported)")

        # Check for duplicate feature names
        if len(set(feature_names)) != len(feature_names):
            raise ModelDataError("Duplicate feature names are not allowed")

        # Validate classes
        classes = model_data['classes']
        if not isinstance(classes, list):
            raise ModelDataError("classes must be a list")

        if len(classes) < 2:
            raise ModelDataError(
                "At least two classes are required for classification")

        if len(classes) > 100:
            raise ModelDataError("Too many classes (max 100 supported)")

        # Check for duplicate class names
        if len(set(classes)) != len(classes):
            raise ModelDataError("Duplicate class names are not allowed")

    def _validate_optimization(self, optimization: str) -> None:
        """
        Validate optimization parameter.

        Args:
            optimization: Optimization level string

        Raises:
            OptimizationError: If validation fails
        """
        if not isinstance(optimization, str):
            raise OptimizationError("optimization must be a string")

        valid_optimizations = ['accuracy', 'speed', 'power', 'balanced']
        if optimization not in valid_optimizations:
            raise OptimizationError(f"Invalid optimization: '{optimization}'. "
                                    f"Valid options: {valid_optimizations}")

    def _validate_platform(self, platform: str) -> None:
        """
        Validate platform parameter.

        Args:
            platform: Target platform string

        Raises:
            ValidationError: If validation fails
        """
        if not isinstance(platform, str):
            raise ValidationError("platform must be a string")

        valid_platforms = ['arduino', 'arm_cortex_m',
                           'esp32', 'm5stack', 'teensy', 'seeed_xiao',
                           'generic_c', 'generic_cpp', 'esp_idf',
                           'micropython', 'zephyr']
        if platform not in valid_platforms:
            raise ValidationError(f"Invalid platform: '{platform}'. "
                                  f"Valid platforms: {valid_platforms}")

    def _validate_parameter_consistency(self) -> None:
        """
        Validate consistency between different model parameters.

        Raises:
            ModelDataError: If parameters are inconsistent
        """
        # Check feature scaling parameter consistency
        if 'feature_means' in self.model_data:
            means = self.model_data['feature_means']
            if not isinstance(means, list):
                raise ModelDataError("feature_means must be a list")

            if len(means) != len(self.feature_names):
                raise ModelDataError(f"feature_means length ({len(means)}) must match "
                                     f"feature_names length ({len(self.feature_names)})")

        if 'feature_stds' in self.model_data:
            stds = self.model_data['feature_stds']
            if not isinstance(stds, list):
                raise ModelDataError("feature_stds must be a list")

            if len(stds) != len(self.feature_names):
                raise ModelDataError(f"feature_stds length ({len(stds)}) must match "
                                     f"feature_names length ({len(self.feature_names)})")

            # Check for zero or negative standard deviations
            for i, std in enumerate(stds):
                if not isinstance(std, (int, float)) or std <= 0:
                    raise ModelDataError(
                        f"feature_stds[{i}] must be a positive number, got {std}")
