"""
CNN Code Generator
Generates C code for 1D-CNN inference on microcontrollers.

The CNN operates on raw sensor windows (no manual feature extraction),
applying Conv1D → ReLU → MaxPool → GlobalAvgPool → Dense layers purely
in C with statically embedded weights.
"""

import numpy as np
from typing import Dict, Any, List
from .base_generator import BaseCodeGenerator
from .quantization import _wrap_c_values


class CNNCodeGenerator(BaseCodeGenerator):
    """Code generator for 1D-CNN models (PyTorch HARCNN)."""

    def __init__(self, model_data: Dict[str, Any], platform: str = 'arduino',
                 optimization: str = 'balanced', overlap: float = 0.5,
                 quantization: str = 'none', **kwargs):
        # CNN doesn't use traditional feature_names — provide channel names
        # as placeholder so the base class validation passes.
        if not model_data.get('feature_names'):
            n_ch = model_data.get('n_channels', 6)
            model_data = dict(model_data)  # shallow copy
            model_data['feature_names'] = [f'ch{i}' for i in range(n_ch)]

        super().__init__(model_data, platform, optimization, overlap, quantization, **kwargs)

        self.layers: List[Dict[str, Any]] = []
        self.n_channels = model_data.get('n_channels', 6)

        self._extract_layers()

    # ------------------------------------------------------------------ #
    # Weight extraction
    # ------------------------------------------------------------------ #

    def _extract_layers(self):
        """Extract CNN layer descriptions (from PyTorchTrainer.export_cnn_weights)."""
        # Try model_object first (live model)
        if 'model_object' in self.model_data:
            model_obj = self.model_data['model_object']
            try:
                if hasattr(model_obj, '_pytorch_trainer'):
                    cnn_export = model_obj._pytorch_trainer.export_cnn_weights()
                    self.layers = cnn_export.get('layers', [])
                    if self.layers:
                        print(f"✅ Extracted CNN layers: {[l['type'] for l in self.layers]}")
                        self._normalise_layers()
                        return
            except Exception as e:
                print(f"Warning: could not extract CNN weights from model object: {e}")

        # Fallback: weights stored in model_data (loaded from .joblib)
        cnn_weights = self.model_data.get('cnn_weights', {})
        if cnn_weights:
            self.layers = cnn_weights.get('layers', [])
            if self.layers:
                print(f"✅ Loaded CNN layers from saved weights: {[l['type'] for l in self.layers]}")
                self._normalise_layers()
                return

        print("⚠️ No CNN weights found — generating placeholder code")

    def _normalise_layers(self):
        """Ensure every layer dict has all expected keys with defaults."""
        for layer in self.layers:
            if layer['type'] == 'conv1d':
                layer.setdefault('padding', 0)
                layer.setdefault('out_channels', len(layer.get('weights', [[]])))
                layer.setdefault('in_channels', len(layer.get('weights', [[[]]])[0]) if layer.get('weights') else 0)
                layer.setdefault('kernel_size', len(layer.get('weights', [[[]]])[0][0]) if layer.get('weights') else 3)
            elif layer['type'] == 'maxpool1d':
                layer.setdefault('kernel_size', 2)
            elif layer['type'] == 'dense':
                layer.setdefault('in_features', 0)
                layer.setdefault('out_features', 0)

    # ------------------------------------------------------------------ #
    # Header
    # ------------------------------------------------------------------ #

    def generate_header(self) -> str:
        """Generate header for CNN model."""
        # Compute intermediate dimensions for buffer sizing
        buf_info = self._compute_buffer_sizes()

        header = f"""/*
 * Human Activity Recognition — 1D-CNN Model
 * Generated by HAR Edge Framework
 * Architecture: Conv1D → ReLU → MaxPool → GlobalAvgPool → Dense
 * Input: {self.window_size} samples × {self.n_channels} channels
 * Classes: {len(self.classes)}
 * Platform: {self.platform}
 * Optimization: {self.optimization.title()}
 * {self._get_quantization_comment()}
 */

#ifndef HAR_CNN_MODEL_H
#define HAR_CNN_MODEL_H

{self._get_platform_includes()}

// ---- Model geometry ----
#define WINDOW_SIZE    {self.window_size}
#define N_CHANNELS     {self.n_channels}
#define NUM_CLASSES    {len(self.classes)}
#define SAMPLING_RATE  {self.sampling_rate}
"""
        # Emit layer-specific #defines
        for i, layer in enumerate(self.layers):
            tag = f"L{i}"
            if layer['type'] == 'conv1d':
                header += f"""
#define {tag}_OUT_CH   {layer['out_channels']}
#define {tag}_IN_CH    {layer['in_channels']}
#define {tag}_KSIZE    {layer['kernel_size']}
#define {tag}_PAD      {layer['padding']}"""
            elif layer['type'] == 'maxpool1d':
                header += f"""
#define {tag}_POOL     {layer['kernel_size']}"""
            elif layer['type'] == 'dense':
                header += f"""
#define {tag}_IN       {layer['in_features']}
#define {tag}_OUT      {layer['out_features']}"""

        header += f"""

// Max intermediate buffer size (floats)
#define CNN_BUF_SIZE   {buf_info['max_buf']}

// Confidence threshold — prediction returns -1 when below this
#define CONFIDENCE_THRESHOLD 0.6f

// Public API
void har_init(void);
int  har_predict_from_window(float window[WINDOW_SIZE][N_CHANNELS], float* confidence);
const char* get_activity_name(int class_id);

#endif /* HAR_CNN_MODEL_H */
"""
        return header

    # ------------------------------------------------------------------ #
    # Implementation
    # ------------------------------------------------------------------ #

    def generate_implementation(self, header_filename: str = None) -> str:
        """Generate full .c / .cpp implementation file."""
        import os
        header_include = os.path.basename(header_filename) if header_filename else "har_cnn_model.h"

        code = f"""/*
 * 1D-CNN Inference Implementation
 * Generated by HAR Edge Framework
 */

#include "{header_include}"
{self._get_impl_includes()}

// Activity names
const char* activity_names[NUM_CLASSES] = {{
    {', '.join(f'"{c}"' for c in self.classes)}
}};

{self._generate_weight_arrays()}

// ==================================================================
// Generic layer functions
// ==================================================================

{self._generate_layer_functions()}

// ==================================================================
// Predict from raw sensor window
// ==================================================================

void har_init(void) {{
    // No initialisation required — weights are const arrays.
}}

// Returns predicted class id, or -1 if confidence is below CONFIDENCE_THRESHOLD.
// If confidence != NULL, the confidence value (0..1) is written to *confidence.
int har_predict_from_window(float window[WINDOW_SIZE][N_CHANNELS], float* confidence) {{
{self._generate_forward_pass()}
}}

const char* get_activity_name(int class_id) {{
    if (class_id >= 0 && class_id < NUM_CLASSES) {{
        return activity_names[class_id];
    }}
    return "unknown";
}}
"""
        return code

    # ------------------------------------------------------------------ #
    # Example sketch
    # ------------------------------------------------------------------ #

    def generate_example_sketch(self, header_filename: str = None) -> str:
        """Generate a platform-appropriate example sketch that reads sensor data and classifies."""
        import os
        header_include = os.path.basename(header_filename) if header_filename else "har_cnn_model.h"

        if self.platform in ('generic_c', 'generic_cpp'):
            return self._generate_cnn_generic_example(header_include)
        elif self.platform == 'esp_idf':
            return self._generate_cnn_esp_idf_example(header_include)
        else:
            return self._generate_cnn_arduino_example(header_include)

    def _generate_cnn_arduino_example(self, header_include: str) -> str:
        """Arduino-style setup()/loop() sketch for CNN.

        Uses the same platform-aware IMU code and millis()-based timing
        as the base generator's Arduino sketch.
        """
        platform_code = self._get_platform_specific_code()
        delay_ms = {
            'speed': 5,
            'power': 50,
            'accuracy': 10,
            'balanced': 10
        }.get(self.optimization, 10)

        sketch = f"""/*
 * HAR 1D-CNN Example Sketch
 * Reads IMU data into a sliding window and runs CNN inference.
 *
 * Generated by HAR Edge Framework
 * Platform: {self.platform}
 * Optimization: {self.optimization.upper()}
 */

#include "{header_include}"

{platform_code['includes']}

{platform_code['defines']}

// Circular buffer for sensor window
static float sensor_window[WINDOW_SIZE][N_CHANNELS];
static int   sample_idx = 0;
static bool  window_ready = false;
unsigned long last_reading = 0;
const unsigned long READING_INTERVAL = 1000 / SAMPLING_RATE; // ms between readings

void setup() {{
    Serial.begin(115200);
    while (!Serial)
        delay(10);

    har_init();

{platform_code['imu_init']}

    Serial.println("HAR 1D-CNN Model Ready!");
    Serial.println("Collecting sensor data...");
}}

void loop() {{
    unsigned long current_time = millis();

    if (current_time - last_reading >= READING_INTERVAL) {{
        last_reading = current_time;

{platform_code['sensor_read']}

        // Store into circular window
        sensor_window[sample_idx][0] = aX;
        sensor_window[sample_idx][1] = aY;
        sensor_window[sample_idx][2] = aZ;
        sensor_window[sample_idx][3] = gX;
        sensor_window[sample_idx][4] = gY;
        sensor_window[sample_idx][5] = gZ;
        sample_idx++;

        if (sample_idx >= WINDOW_SIZE) {{
            window_ready = true;
            sample_idx = 0;
        }}

        // Run inference when a full window is available
        static const char* last_activity = NULL;
        if (window_ready) {{
            float confidence = 0.0f;
            int prediction = har_predict_from_window(sensor_window, &confidence);
            if (prediction >= 0) {{
                last_activity = get_activity_name(prediction);
            }}

            // Debug: log prediction (lines starting with # are ignored by parser)
            Serial.print("# PRED: class="); Serial.print(prediction);
            Serial.print(" conf="); Serial.print(confidence, 4);
            Serial.print(" name="); Serial.println(prediction >= 0 ? last_activity : "none");

            window_ready = false;   // wait for next full window
        }}

        // Always output sensor CSV (for Device Test graph plotting)
        // Append last prediction on every line so Device Test tab always has it
        Serial.print(aX, 4); Serial.print(",");
        Serial.print(aY, 4); Serial.print(",");
        Serial.print(aZ, 4); Serial.print(",");
        Serial.print(gX, 4); Serial.print(",");
        Serial.print(gY, 4); Serial.print(",");
        Serial.print(gZ, 4);
        if (last_activity != NULL) {{
            Serial.print(",");
            Serial.print(last_activity);
        }}
        Serial.println();
    }}

    delay({delay_ms});  // Optimization-specific delay
}}
"""
        return sketch

    def _generate_cnn_generic_example(self, header_include: str) -> str:
        """Portable C/C++ main() example for CNN."""
        is_cpp = self.platform == 'generic_cpp'
        ext = 'cpp' if is_cpp else 'c'
        io_include = '<cstdio>' if is_cpp else '<stdio.h>'

        return f"""/*
 * HAR 1D-CNN \u2014 Portable {('C++' if is_cpp else 'C')} Example
 * Compile: {'g++' if is_cpp else 'gcc'} -O2 -o har_cnn_example example.{ext} har_cnn_model.{ext} -lm
 */

#include "{header_include}"
#include {io_include}

static int read_sensor_window(float window[][N_CHANNELS]) {{
    /* REPLACE with real sensor/file reading code */
    for (int i = 0; i < WINDOW_SIZE; i++)
        for (int c = 0; c < N_CHANNELS; c++)
            window[i][c] = 0.0f;
    return 0;
}}

int main(void) {{
    har_init();
    printf("HAR 1D-CNN model ready\\n");

    float window[WINDOW_SIZE][N_CHANNELS];
    if (read_sensor_window(window) == 0) {{
        int cls = har_predict_from_window(window, NULL);
        printf("Prediction: %s\\n", get_activity_name(cls));
    }}
    return 0;
}}
"""

    def _generate_cnn_esp_idf_example(self, header_include: str) -> str:
        """ESP-IDF app_main() example for CNN."""
        return f"""/*
 * HAR 1D-CNN \u2014 ESP-IDF Example
 */

#include "{header_include}"
#include "esp_log.h"

static const char *TAG = "HAR_CNN";

void app_main(void) {{
    har_init();
    ESP_LOGI(TAG, "HAR 1D-CNN model ready");

    float window[WINDOW_SIZE][N_CHANNELS];
    /* TODO: fill window from IMU */

    int cls = har_predict_from_window(window, NULL);
    ESP_LOGI(TAG, "Prediction: %s", get_activity_name(cls));
}}
"""

    # ------------------------------------------------------------------ #
    # ---- internal helpers ---
    # ------------------------------------------------------------------ #

    def _get_model_specific_declarations(self) -> str:
        """Required by base class — CNN uses its own header."""
        return ""

    def _generate_model_specific_implementation(self) -> str:
        """Required by base class — CNN uses its own implementation."""
        return ""

    def _generate_prediction_function(self) -> str:
        """Required by base class — CNN uses har_predict_from_window."""
        return ""

    def _generate_utility_functions(self) -> str:
        return ""

    # ---- layer functions ----

    def _generate_layer_functions(self) -> str:
        """Generate conv1d, maxpool1d, global_avg_pool, dense functions.
        
        When quantization is active, the conv1d and dense functions accept
        quantized weight pointers and a scale factor.
        """
        from .quantization import get_c_type

        maxpool_fn = """
/**
 * 1D max-pooling with stride = kernel_size (no overlap).
 */
static void maxpool1d(const float *input, float *output,
                      int seq_len, int channels, int pool_k) {
    int out_len = seq_len / pool_k;
    for (int t = 0; t < out_len; t++) {
        for (int c = 0; c < channels; c++) {
            float mx = -1e30f;
            for (int p = 0; p < pool_k; p++) {
                float v = input[(t * pool_k + p) * channels + c];
                if (v > mx) mx = v;
            }
            output[t * channels + c] = mx;
        }
    }
}"""
        gap_fn = """
/**
 * Global average pooling over the time dimension.
 */
static void global_avg_pool(const float *input, float *output,
                            int seq_len, int channels) {
    for (int c = 0; c < channels; c++) {
        float sum = 0.0f;
        for (int t = 0; t < seq_len; t++) {
            sum += input[t * channels + c];
        }
        output[c] = sum / (float)seq_len;
    }
}"""

        if self.quantization in ('int8', 'int16'):
            c_type = get_c_type(self.quantization)
            conv_fn = f"""
/**
 * Quantized 1D convolution ({self.quantization.upper()} weights, float activations).
 * weights are {c_type}, dequantized on-the-fly via scale factor.
 */
static void conv1d(const float *input, float *output,
                   const {c_type} *weights, const float *bias, float w_scale,
                   int seq_len, int in_ch, int out_ch,
                   int kernel_size, int padding) {{
    for (int o = 0; o < out_ch; o++) {{
        for (int t = 0; t < seq_len; t++) {{
            float sum = bias[o];
            for (int ic = 0; ic < in_ch; ic++) {{
                for (int k = 0; k < kernel_size; k++) {{
                    int pos = t - padding + k;
                    if (pos >= 0 && pos < seq_len) {{
                        sum += input[pos * in_ch + ic]
                             * ((float)weights[(o * in_ch + ic) * kernel_size + k] * w_scale);
                    }}
                }}
            }}
            // fused ReLU
            output[t * out_ch + o] = (sum > 0.0f) ? sum : 0.0f;
        }}
    }}
}}"""
            dense_fn = f"""
/**
 * Quantized fully-connected layer ({self.quantization.upper()} weights, float bias).
 */
static void dense(const float *input, float *output,
                  const {c_type} *weights, const float *bias, float w_scale,
                  int in_features, int out_features, int apply_relu) {{
    for (int o = 0; o < out_features; o++) {{
        float sum = bias[o];
        for (int i = 0; i < in_features; i++) {{
            sum += input[i] * ((float)weights[i * out_features + o] * w_scale);
        }}
        output[o] = (apply_relu && sum < 0.0f) ? 0.0f : sum;
    }}
}}"""
        else:
            # float32 or float16 (both emit float arrays)
            conv_fn = """
/**
 * 1D convolution  (same-padding when pad = kernel_size/2).
 * input  : [seq_len][in_ch]
 * output : [seq_len][out_ch]
 * weights: [out_ch][in_ch][kernel_size]
 */
static void conv1d(const float *input, float *output,
                   const float *weights, const float *bias,
                   int seq_len, int in_ch, int out_ch,
                   int kernel_size, int padding) {
    for (int o = 0; o < out_ch; o++) {
        for (int t = 0; t < seq_len; t++) {
            float sum = bias[o];
            for (int ic = 0; ic < in_ch; ic++) {
                for (int k = 0; k < kernel_size; k++) {
                    int pos = t - padding + k;
                    if (pos >= 0 && pos < seq_len) {
                        sum += input[pos * in_ch + ic]
                             * weights[(o * in_ch + ic) * kernel_size + k];
                    }
                }
            }
            // fused ReLU
            output[t * out_ch + o] = (sum > 0.0f) ? sum : 0.0f;
        }
    }
}"""
            dense_fn = """
/**
 * Fully-connected (dense) layer with optional ReLU.
 */
static void dense(const float *input, float *output,
                  const float *weights, const float *bias,
                  int in_features, int out_features, int apply_relu) {
    for (int o = 0; o < out_features; o++) {
        float sum = bias[o];
        for (int i = 0; i < in_features; i++) {
            sum += input[i] * weights[i * out_features + o];
        }
        output[o] = (apply_relu && sum < 0.0f) ? 0.0f : sum;
    }
}"""

        return conv_fn + maxpool_fn + gap_fn + dense_fn

    # ---- weight arrays ----

    def _generate_weight_arrays(self) -> str:
        """Emit weight arrays for every parameterised layer.
        
        When quantization is enabled, emits int8/int16 arrays + scale factors
        instead of float arrays.
        """
        if self.quantization != 'none':
            return self._generate_quantized_weight_arrays()
        return self._generate_float_weight_arrays()

    def _generate_float_weight_arrays(self) -> str:
        """Emit const float arrays for every parameterised layer (original path)."""
        parts: List[str] = []
        for i, layer in enumerate(self.layers):
            tag = f"l{i}"
            if layer['type'] == 'conv1d':
                w = np.array(layer['weights'])           # (out_ch, in_ch, k)
                b = np.array(layer['bias'])               # (out_ch,)
                parts.append(self._fmt_3d(w, f"{tag}_w"))
                parts.append(self._fmt_1d(b, f"{tag}_b"))
            elif layer['type'] == 'dense':
                w = np.array(layer['weights'])            # (in, out)
                b = np.array(layer['bias'])               # (out,)
                parts.append(self._fmt_2d(w, f"{tag}_w"))
                parts.append(self._fmt_1d(b, f"{tag}_b"))
        return "\n\n".join(parts)

    def _generate_quantized_weight_arrays(self) -> str:
        """Emit quantized weight arrays + scale factors + info comment."""
        from .quantization import (
            quantize_tensor, format_quantized_1d, format_quantized_2d,
            format_quantized_3d, generate_quantization_info_comment,
            generate_dequant_helper, QuantizationReport, compute_quantization_error,
        )

        mode = self.quantization
        report = QuantizationReport(mode=mode)
        parts: List[str] = []

        for i, layer in enumerate(self.layers):
            tag = f"l{i}"
            if layer['type'] == 'conv1d':
                w = np.array(layer['weights'], dtype=np.float32)  # (out_ch, in_ch, k)
                b = np.array(layer['bias'], dtype=np.float32)
                qt_w = quantize_tensor(w, mode)
                report.tensors[f'{tag}_w'] = qt_w
                parts.append(format_quantized_3d(
                    qt_w, f"{tag}_w", w.shape[0], w.shape[1], w.shape[2],
                    precision=self.feature_precision, static=True))
                # Biases stay float for numerical accuracy
                parts.append(self._fmt_1d(b, f"{tag}_b"))
            elif layer['type'] == 'dense':
                w = np.array(layer['weights'], dtype=np.float32)
                b = np.array(layer['bias'], dtype=np.float32)
                qt_w = quantize_tensor(w, mode)
                report.tensors[f'{tag}_w'] = qt_w
                parts.append(format_quantized_2d(
                    qt_w, f"{tag}_w", w.shape[0], w.shape[1],
                    precision=self.feature_precision, static=True))
                parts.append(self._fmt_1d(b, f"{tag}_b"))

        # Compute totals
        for name, qt in report.tensors.items():
            report.total_quantized_bytes += qt.memory_bytes
            report.total_original_bytes += qt.original_bytes

        info = generate_quantization_info_comment(report)
        dequant = generate_dequant_helper(mode)

        return info + '\n\n' + '\n\n'.join(parts) + '\n' + dequant

    def _fmt_1d(self, arr: np.ndarray, name: str) -> str:
        """Format 1-D array as const float[]."""
        prec = self.feature_precision
        vals = ", ".join(f"{v:.{prec}f}" for v in arr.flat)
        return f"static const float {name}[{arr.size}] = {{\n    {self._wrap_vals(vals)}\n}};"

    def _fmt_2d(self, arr: np.ndarray, name: str) -> str:
        """Format 2-D array as flattened const float[] (row-major)."""
        prec = self.feature_precision
        vals = ", ".join(f"{v:.{prec}f}" for v in arr.flat)
        return (f"// shape ({arr.shape[0]}, {arr.shape[1]})\n"
                f"static const float {name}[{arr.size}] = {{\n    {self._wrap_vals(vals)}\n}};")

    def _fmt_3d(self, arr: np.ndarray, name: str) -> str:
        """Format 3-D array as flattened const float[] (C-contiguous)."""
        prec = self.feature_precision
        vals = ", ".join(f"{v:.{prec}f}" for v in arr.flat)
        return (f"// shape ({arr.shape[0]}, {arr.shape[1]}, {arr.shape[2]})\n"
                f"static const float {name}[{arr.size}] = {{\n    {self._wrap_vals(vals)}\n}};")

    @staticmethod
    def _wrap_vals(vals: str, width: int = 100) -> str:
        """Insert newlines every ~`width` characters for readability.

        Delegates to the shared implementation in quantization module.
        """
        return _wrap_c_values(vals, width)

    # ---- forward-pass code generation ----

    def _compute_buffer_sizes(self) -> Dict[str, int]:
        """Walk the layer list and compute the maximum intermediate buffer size."""
        seq_len = self.window_size
        channels = self.n_channels
        max_buf = seq_len * channels  # input size

        for layer in self.layers:
            if layer['type'] == 'conv1d':
                channels = layer['out_channels']
                buf = seq_len * channels
            elif layer['type'] == 'maxpool1d':
                seq_len = seq_len // layer['kernel_size']
                buf = seq_len * channels
            elif layer['type'] == 'dense':
                buf = max(layer['in_features'], layer['out_features'])
            else:
                buf = 0
            if buf > max_buf:
                max_buf = buf
        return {'max_buf': max_buf}

    def _generate_forward_pass(self) -> str:
        """Generate the body of har_predict_from_window()."""
        lines: List[str] = []
        buf_info = self._compute_buffer_sizes()
        is_quantized = self.quantization in ('int8', 'int16')

        # We ping-pong between two large buffers to avoid extra copies.
        lines.append(f"    static float buf_a[CNN_BUF_SIZE];")
        lines.append(f"    static float buf_b[CNN_BUF_SIZE];")
        lines.append(f"")

        # Copy input window into buf_a (flatten [WINDOW_SIZE][N_CHANNELS] → [WINDOW_SIZE * N_CHANNELS])
        lines.append(f"    // Copy input into working buffer")
        lines.append(f"    for (int t = 0; t < WINDOW_SIZE; t++) {{")
        lines.append(f"        for (int c = 0; c < N_CHANNELS; c++) {{")
        lines.append(f"            buf_a[t * N_CHANNELS + c] = window[t][c];")
        lines.append(f"        }}")
        lines.append(f"    }}")
        lines.append(f"")

        src, dst = "buf_a", "buf_b"
        seq_len_expr = "WINDOW_SIZE"
        ch_expr = "N_CHANNELS"
        dense_idx = 0  # track dense layers for ReLU decision

        # Count total dense layers to know which is last
        total_dense = sum(1 for l in self.layers if l['type'] == 'dense')

        for i, layer in enumerate(self.layers):
            tag = f"l{i}"
            if layer['type'] == 'conv1d':
                lines.append(f"    // Layer {i}: Conv1D({layer['in_channels']}→{layer['out_channels']}, k={layer['kernel_size']}, pad={layer['padding']}) + ReLU")
                if is_quantized:
                    lines.append(f"    conv1d({src}, {dst}, {tag}_w, {tag}_b, {tag}_w_scale,")
                else:
                    lines.append(f"    conv1d({src}, {dst}, {tag}_w, {tag}_b,")
                lines.append(f"           {seq_len_expr}, L{i}_IN_CH, L{i}_OUT_CH, L{i}_KSIZE, L{i}_PAD);")
                ch_expr = f"L{i}_OUT_CH"
                src, dst = dst, src  # swap
                lines.append("")

            elif layer['type'] == 'maxpool1d':
                pool_k = layer['kernel_size']
                lines.append(f"    // Layer {i}: MaxPool1D(k={pool_k})")
                new_seq = f"({seq_len_expr} / L{i}_POOL)"
                lines.append(f"    maxpool1d({src}, {dst}, {seq_len_expr}, {ch_expr}, L{i}_POOL);")
                seq_len_expr = new_seq
                src, dst = dst, src
                lines.append("")

            elif layer['type'] == 'dense':
                dense_idx += 1
                is_last = (dense_idx == total_dense)
                relu_flag = "0" if is_last else "1"
                relu_comment = "" if is_last else " + ReLU"

                # Extra scale argument for quantized weights
                scale_arg = f", {tag}_w_scale" if is_quantized else ""

                if dense_idx == 1:
                    # First dense layer — preceded by global avg pool
                    lines.append(f"    // Global average pooling → {layer['in_features']} features")
                    lines.append(f"    float gap_out[L{i}_IN];")
                    lines.append(f"    global_avg_pool({src}, gap_out, {seq_len_expr}, {ch_expr});")
                    lines.append(f"")
                    lines.append(f"    // Layer {i}: Dense({layer['in_features']}→{layer['out_features']}){relu_comment}")
                    lines.append(f"    float d{dense_idx}_out[L{i}_OUT];")
                    lines.append(f"    dense(gap_out, d{dense_idx}_out, {tag}_w, {tag}_b{scale_arg}, L{i}_IN, L{i}_OUT, {relu_flag});")
                    lines.append("")
                else:
                    prev_out = f"d{dense_idx-1}_out"
                    lines.append(f"    // Layer {i}: Dense({layer['in_features']}→{layer['out_features']}){relu_comment}")
                    lines.append(f"    float d{dense_idx}_out[L{i}_OUT];")
                    lines.append(f"    dense({prev_out}, d{dense_idx}_out, {tag}_w, {tag}_b{scale_arg}, L{i}_IN, L{i}_OUT, {relu_flag});")
                    lines.append("")

        # Softmax + confidence + threshold over final dense output
        final_dense_var = f"d{dense_idx}_out"
        final_dense_layer = [l for l in self.layers if l['type'] == 'dense'][-1]
        final_idx = self.layers.index(final_dense_layer)
        lines.append(f"    // Softmax: convert logits to probabilities")
        lines.append(f"    float max_logit = {final_dense_var}[0];")
        lines.append(f"    for (int i = 1; i < L{final_idx}_OUT; i++) {{")
        lines.append(f"        if ({final_dense_var}[i] > max_logit) max_logit = {final_dense_var}[i];")
        lines.append(f"    }}")
        lines.append(f"    float probs[L{final_idx}_OUT];")
        lines.append(f"    float sum_exp = 0.0f;")
        lines.append(f"    for (int i = 0; i < L{final_idx}_OUT; i++) {{")
        lines.append(f"        probs[i] = expf({final_dense_var}[i] - max_logit);")
        lines.append(f"        sum_exp += probs[i];")
        lines.append(f"    }}")
        lines.append(f"    float max_prob = 0.0f;")
        lines.append(f"    int best = 0;")
        lines.append(f"    for (int i = 0; i < L{final_idx}_OUT; i++) {{")
        lines.append(f"        probs[i] /= sum_exp;")
        lines.append(f"        if (probs[i] > max_prob) {{")
        lines.append(f"            max_prob = probs[i];")
        lines.append(f"            best = i;")
        lines.append(f"        }}")
        lines.append(f"    }}")
        lines.append(f"    if (confidence) *confidence = max_prob;")
        lines.append(f"    if (max_prob < CONFIDENCE_THRESHOLD) return -1;")
        lines.append(f"    return best;")

        return "\n".join(lines)

    # ---- platform-specific IMU code (delegates to base_generator) ----

    def _get_platform_specific_code(self) -> dict:
        """Get platform-specific code snippets.

        Delegates to ``BaseCodeGenerator._get_platform_specific_code()`` so
        that any future changes to IMU init, sensor reading, or conversion
        constants automatically propagate here.
        """
        return super()._get_platform_specific_code()