"""
Edge Deployment Code Generation Templates
Generates optimized code for different microcontroller platforms
"""

import numpy as np
import json
from typing import Dict, List, Any, Optional
import os


class ArduinoCodeGenerator:
    """Generate Arduino C++ code for HAR models."""
    
    def __init__(self, model_data: Dict[str, Any]):
        self.model_data = model_data
        self.model_type = model_data.get('model_type', 'unknown')
        self.feature_names = model_data.get('feature_names', [])
        self.classes = model_data.get('classes', [])
    
    def generate_header(self) -> str:
        """Generate header file content."""
        header = f"""
/*
 * Human Activity Recognition Model
 * Generated by HAR Edge Framework
 * Model Type: {self.model_type}
 * Features: {len(self.feature_names)}
 * Classes: {len(self.classes)}
 */

#ifndef HAR_MODEL_H
#define HAR_MODEL_H

#include <Arduino.h>

// Model configuration
#define NUM_FEATURES {len(self.feature_names)}
#define NUM_CLASSES {len(self.classes)}
#define SAMPLING_RATE 100
#define WINDOW_SIZE 100

// Activity classes
enum ActivityClass {{
    {', '.join([f'{cls.upper()} = {i}' for i, cls in enumerate(self.classes)])}
}};

// Function declarations
void har_init();
int har_predict(float features[NUM_FEATURES]);
void extract_features(float sensor_data[][6], int samples, float features[]);
const char* get_activity_name(int class_id);

#endif // HAR_MODEL_H
"""
        return header.strip()
    
    def generate_implementation(self) -> str:
        """Generate implementation file content."""
        implementation = f"""
/*
 * Human Activity Recognition Model Implementation
 * Generated by HAR Edge Framework
 */

#include "har_model.h"
#include <math.h>

// Activity class names
const char* activity_names[NUM_CLASSES] = {{
    {', '.join([f'"{cls}"' for cls in self.classes])}
}};

// Model weights and parameters (placeholder - actual values from trained model)
// Note: Real implementation would include actual model parameters

void har_init() {{
    // Initialize model parameters
    Serial.println("HAR Model initialized");
    Serial.print("Features: ");
    Serial.println(NUM_FEATURES);
    Serial.print("Classes: ");
    Serial.println(NUM_CLASSES);
}}

int har_predict(float features[NUM_FEATURES]) {{
    // Placeholder prediction logic
    // Real implementation would use actual {self.model_type} algorithm
    
    // Simple example: return class based on first feature
    float max_val = features[0];
    int predicted_class = 0;
    
    for (int i = 1; i < NUM_FEATURES; i++) {{
        if (features[i] > max_val) {{
            max_val = features[i];
            predicted_class = i % NUM_CLASSES;
        }}
    }}
    
    return predicted_class;
}}

void extract_features(float sensor_data[][6], int samples, float features[]) {{
    // Extract time-domain features from sensor data
    // sensor_data columns: aX, aY, aZ, gX, gY, gZ
    
    int feature_idx = 0;
    
    // For each sensor axis
    for (int axis = 0; axis < 6; axis++) {{
        float sum = 0.0, sum_sq = 0.0;
        float min_val = sensor_data[0][axis];
        float max_val = sensor_data[0][axis];
        
        // Calculate basic statistics
        for (int i = 0; i < samples; i++) {{
            float val = sensor_data[i][axis];
            sum += val;
            sum_sq += val * val;
            
            if (val < min_val) min_val = val;
            if (val > max_val) max_val = val;
        }}
        
        float mean = sum / samples;
        float variance = (sum_sq / samples) - (mean * mean);
        float std_dev = sqrt(variance);
        
        // Store features
        features[feature_idx++] = mean;          // Mean
        features[feature_idx++] = std_dev;       // Standard deviation
        features[feature_idx++] = min_val;       // Minimum
        features[feature_idx++] = max_val;       // Maximum
        features[feature_idx++] = max_val - min_val; // Range
        features[feature_idx++] = sqrt(sum_sq / samples); // RMS
    }}
}}

const char* get_activity_name(int class_id) {{
    if (class_id >= 0 && class_id < NUM_CLASSES) {{
        return activity_names[class_id];
    }}
    return "UNKNOWN";
}}

// Example usage function
void example_usage() {{
    // Example sensor data buffer
    float sensor_buffer[WINDOW_SIZE][6];
    float features[NUM_FEATURES];
    
    // Fill sensor_buffer with actual IMU data...
    
    // Extract features
    extract_features(sensor_buffer, WINDOW_SIZE, features);
    
    // Make prediction
    int predicted_class = har_predict(features);
    
    // Get activity name
    const char* activity = get_activity_name(predicted_class);
    
    Serial.print("Predicted activity: ");
    Serial.println(activity);
}}
"""
        return implementation.strip()
    
    def generate_example_sketch(self) -> str:
        """Generate example Arduino sketch."""
        sketch = """
/*
 * HAR Model Example Sketch
 * Demonstrates usage of the generated HAR model
 */

#include "har_model.h"

// IMU sensor pins (adjust for your hardware)
#define IMU_SDA_PIN A4
#define IMU_SCL_PIN A5

// Data collection variables
float sensor_buffer[WINDOW_SIZE][6];
int buffer_index = 0;
unsigned long last_reading = 0;
const unsigned long READING_INTERVAL = 1000 / SAMPLING_RATE; // milliseconds

void setup() {
    Serial.begin(9600);
    while (!Serial) delay(10);
    
    Serial.println("HAR Model Demo");
    Serial.println("==============");
    
    // Initialize HAR model
    har_init();
    
    // Initialize IMU sensor (placeholder)
    // Add your IMU initialization code here
    Serial.println("IMU sensor initialized");
    
    Serial.println("Starting activity recognition...");
}

void loop() {
    unsigned long current_time = millis();
    
    // Check if it's time for a new reading
    if (current_time - last_reading >= READING_INTERVAL) {
        last_reading = current_time;
        
        // Read IMU data (placeholder - replace with actual sensor reading)
        float aX = random(-20, 20) / 10.0;  // Simulated accelerometer
        float aY = random(-20, 20) / 10.0;
        float aZ = random(80, 120) / 10.0;
        float gX = random(-50, 50) / 100.0; // Simulated gyroscope
        float gY = random(-50, 50) / 100.0;
        float gZ = random(-50, 50) / 100.0;
        
        // Store in buffer
        sensor_buffer[buffer_index][0] = aX;
        sensor_buffer[buffer_index][1] = aY;
        sensor_buffer[buffer_index][2] = aZ;
        sensor_buffer[buffer_index][3] = gX;
        sensor_buffer[buffer_index][4] = gY;
        sensor_buffer[buffer_index][5] = gZ;
        
        buffer_index++;
        
        // When buffer is full, make prediction
        if (buffer_index >= WINDOW_SIZE) {
            float features[NUM_FEATURES];
            
            // Extract features from the collected data
            extract_features(sensor_buffer, WINDOW_SIZE, features);
            
            // Make prediction
            int predicted_class = har_predict(features);
            const char* activity = get_activity_name(predicted_class);
            
            // Display result
            Serial.print("Predicted Activity: ");
            Serial.println(activity);
            
            // Reset buffer
            buffer_index = 0;
        }
    }
    
    // Small delay to prevent overwhelming the serial monitor
    delay(10);
}
"""
        return sketch.strip()


class CortexMCodeGenerator:
    """Generate ARM Cortex-M C code for HAR models."""
    
    def __init__(self, model_data: Dict[str, Any]):
        self.model_data = model_data
        self.model_type = model_data.get('model_type', 'unknown')
        self.feature_names = model_data.get('feature_names', [])
        self.classes = model_data.get('classes', [])
    
    def generate_code(self) -> str:
        """Generate optimized C code for ARM Cortex-M."""
        code = f"""
/*
 * HAR Model for ARM Cortex-M
 * Optimized for memory and power efficiency
 */

#include <stdint.h>
#include <math.h>
#include <string.h>

#define NUM_FEATURES {len(self.feature_names)}
#define NUM_CLASSES {len(self.classes)}
#define WINDOW_SIZE 100
#define SAMPLING_RATE 100

// Fixed-point arithmetic for efficiency (16.16 format)
typedef int32_t fixed_t;
#define FIXED_SCALE 65536
#define TO_FIXED(x) ((fixed_t)((x) * FIXED_SCALE))
#define FROM_FIXED(x) ((float)(x) / FIXED_SCALE)

// Activity classes
typedef enum {{
    {', '.join([f'{cls.upper()} = {i}' for i, cls in enumerate(self.classes)])}
}} activity_class_t;

// Sensor data structure
typedef struct {{
    fixed_t ax, ay, az;  // Accelerometer
    fixed_t gx, gy, gz;  // Gyroscope
}} sensor_sample_t;

// Feature extraction (optimized for Cortex-M)
void extract_features_cortex(sensor_sample_t* samples, uint16_t count, fixed_t* features) {{
    uint16_t feature_idx = 0;
    
    // Process each sensor axis
    fixed_t* sensor_axes[6] = {{&samples[0].ax, &samples[0].ay, &samples[0].az,
                               &samples[0].gx, &samples[0].gy, &samples[0].gz}};
    
    for (uint8_t axis = 0; axis < 6; axis++) {{
        fixed_t sum = 0, sum_sq = 0;
        fixed_t min_val = sensor_axes[axis][0];
        fixed_t max_val = sensor_axes[axis][0];
        
        // Calculate statistics with fixed-point arithmetic
        for (uint16_t i = 0; i < count; i++) {{
            fixed_t val = *((fixed_t*)((uint8_t*)samples + i*sizeof(sensor_sample_t) + axis*sizeof(fixed_t)));
            sum += val;
            sum_sq += (val >> 8) * (val >> 8); // Avoid overflow
            
            if (val < min_val) min_val = val;
            if (val > max_val) max_val = val;
        }}
        
        fixed_t mean = sum / count;
        
        features[feature_idx++] = mean;
        features[feature_idx++] = max_val - min_val; // Range
        // Add more features as needed...
    }}
}}

// Simplified prediction function
activity_class_t har_predict_cortex(fixed_t* features) {{
    // Optimized prediction algorithm for {self.model_type}
    // Implementation would depend on the specific trained model
    
    // Simple classifier based on feature thresholds
    if (features[0] > TO_FIXED(0.5)) {{
        return {self.classes[0].upper() if self.classes else 'UNKNOWN'};
    }} else {{
        return {self.classes[-1].upper() if self.classes else 'UNKNOWN'};
    }}
}}

// Power-efficient processing
void process_sensor_data_low_power(sensor_sample_t* buffer, uint16_t* buffer_idx, 
                                   sensor_sample_t new_sample) {{
    buffer[*buffer_idx] = new_sample;
    (*buffer_idx)++;
    
    if (*buffer_idx >= WINDOW_SIZE) {{
        fixed_t features[NUM_FEATURES];
        extract_features_cortex(buffer, WINDOW_SIZE, features);
        
        activity_class_t prediction = har_predict_cortex(features);
        
        // Handle prediction result...
        
        *buffer_idx = 0; // Reset buffer
    }}
}}
"""
        return code.strip()


def generate_deployment_code(model_data: Dict[str, Any], 
                           platform: str = 'arduino',
                           optimization: str = 'balanced') -> Dict[str, str]:
    """
    Generate deployment code for specified platform.
    
    Args:
        model_data: Trained model data and parameters
        platform: Target platform ('arduino', 'arm_cortex_m', 'seeed_xiao')
        optimization: Optimization strategy ('accuracy', 'speed', 'power', 'balanced')
    
    Returns:
        Dictionary containing generated code files
    """
    
    if platform == 'arduino' or platform == 'seeed_xiao':
        generator = ArduinoCodeGenerator(model_data)
        return {
            'har_model.h': generator.generate_header(),
            'har_model.cpp': generator.generate_implementation(),
            'har_example.ino': generator.generate_example_sketch()
        }
    
    elif platform == 'arm_cortex_m':
        generator = CortexMCodeGenerator(model_data)
        return {
            'har_model_cortex.c': generator.generate_code()
        }
    
    else:
        raise ValueError(f"Unsupported platform: {platform}")


def analyze_resource_requirements(model_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Analyze memory and computational requirements for edge deployment.
    
    Args:
        model_data: Trained model data
    
    Returns:
        Resource analysis results
    """
    
    num_features = len(model_data.get('feature_names', []))
    num_classes = len(model_data.get('classes', []))
    model_type = model_data.get('model_type', 'unknown')
    
    # Estimate memory requirements
    feature_memory = num_features * 4  # 4 bytes per float feature
    buffer_memory = 100 * 6 * 4  # Sensor buffer (100 samples, 6 axes, 4 bytes each)
    
    # Model-specific memory estimation
    if model_type == 'random_forest':
        # Rough estimate: trees * nodes * parameters
        model_memory = 1000 * 50 * 8  # Conservative estimate
    elif model_type == 'svm':
        # Support vectors * features * parameters
        model_memory = 100 * num_features * 8
    elif model_type == 'neural_network':
        # Weights and biases estimation
        model_memory = num_features * 100 * 4 + 100 * num_classes * 4
    else:
        model_memory = 1000  # Default estimate
    
    total_memory = feature_memory + buffer_memory + model_memory
    
    # Computational complexity estimation
    operations_per_prediction = num_features * 10  # Rough estimate
    
    return {
        'memory_requirements': {
            'feature_memory_bytes': feature_memory,
            'buffer_memory_bytes': buffer_memory,
            'model_memory_bytes': model_memory,
            'total_memory_bytes': total_memory,
            'total_memory_kb': total_memory // 1024
        },
        'computational_requirements': {
            'operations_per_prediction': operations_per_prediction,
            'estimated_inference_time_ms': operations_per_prediction / 1000,  # Rough estimate
            'power_consumption_estimate': 'Low' if total_memory < 32768 else 'Medium'
        },
        'platform_compatibility': {
            'arduino_uno': total_memory < 2048,
            'arduino_nano_33': total_memory < 262144,
            'seeed_xiao_nrf52840': total_memory < 262144,
            'esp32': total_memory < 524288
        }
    }
