"""
ZephyrSketch — generates Zephyr RTOS main.c + CMakeLists.txt + prj.conf.

The C++ core files (har_config.h, har_features.h/.cpp, har_model.h/.cpp,
har_classifier.h/.cpp) are shared with the Arduino platform — only the
application entry point changes.
"""

from __future__ import annotations
from typing import List

from .base import PlatformSketch


class ZephyrSketch(PlatformSketch):
    """
    Generates Zephyr RTOS application files for HAR inference.

    Produced files (returned by generate_files()):
      main.c           — app_main() using Zephyr sensor subsystem
      CMakeLists.txt   — minimal CMake project
      prj.conf         — Kconfig flags required at build time

    The C++ model/feature/classifier files are identical to the Arduino
    build and are generated by the standard FeatureBlock / ModelBlock /
    ClassifierBlock pipeline.

    Serial output (Zephyr LOG_INF):
      CSV: aX,aY,aZ,gX,gY,gZ[,activity_name]  (every sample)
      Debug lines start with '#' and are ignored by the Device Test parser.
    """

    def generate(self) -> str:
        """Return main.c content."""
        return self._main_c()

    def generate_files(self) -> dict:
        """Return all Zephyr application files."""
        return {
            "main.c": self._main_c(),
            "CMakeLists.txt": self._cmake(),
            "prj.conf": self._prj_conf(),
        }

    # ------------------------------------------------------------------
    # main.c
    # ------------------------------------------------------------------

    def _main_c(self) -> str:
        delay_ms = max(1, int(1000 * self.step_size / max(self.sampling_rate, 1)))
        sample_interval_ms = max(1, int(1000 / max(self.sampling_rate, 1)))
        class_names = ", ".join(f'"{c}"' for c in self.classes)

        return f"""\
/*
 * HAR Inference — Zephyr RTOS
 * Generated by HAR Edge Framework v2
 *
 * Build:
 *   west build -b <your_board>
 *   west flash
 *
 * Serial output (UART):
 *   CSV line every sample:  aX,aY,aZ,gX,gY,gZ[,activity_name]
 *   '#'-prefixed lines are debug info (ignored by the Device Test parser).
 *
 * Adjust IMU_NODE in the device tree overlay for your board.
 */

#include "har_classifier.h"

#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/drivers/sensor.h>
#include <stdio.h>
#include <string.h>

LOG_MODULE_REGISTER(har_main, LOG_LEVEL_INF);

/* ---------- Device-tree binding ----------
 * Define an 'imu0' alias in your board overlay pointing to your IMU.
 * Common examples:
 *   &lsm6ds3      (Seeed XIAO nRF52840 Sense)
 *   &mpu6050      (breakout boards)
 *   &icm42688p    (Nordic Thingy:53)
 */
#define IMU_NODE DT_ALIAS(imu0)

#if DT_NODE_HAS_STATUS(IMU_NODE, okay)
static const struct device *const imu_dev = DEVICE_DT_GET(IMU_NODE);
#else
/* Fallback: try to get any accelerometer — may fail at runtime */
#warning "No 'imu0' alias found in device tree. Please add one."
static const struct device *imu_dev;
#endif

/* ---------- Window buffer ---------- */
static float sensor_window[HAR_WINDOW_SIZE][HAR_N_CHANNELS];
static int   sample_idx   = 0;
static bool  window_ready = false;

static const char *last_activity = NULL;

/* ---------- Sensor read helper ---------- */

static int read_one_sample(float *ax, float *ay, float *az,
                           float *gx, float *gy, float *gz)
{{
    struct sensor_value accel[3], gyro[3];

    if (sensor_sample_fetch(imu_dev) < 0) {{
        LOG_ERR("sensor_sample_fetch failed");
        return -1;
    }}

    sensor_channel_get(imu_dev, SENSOR_CHAN_ACCEL_XYZ, accel);
    sensor_channel_get(imu_dev, SENSOR_CHAN_GYRO_XYZ,  gyro);

    /* accel: Zephyr delivers m/s², no conversion needed */
    *ax = (float)sensor_value_to_double(&accel[0]);
    *ay = (float)sensor_value_to_double(&accel[1]);
    *az = (float)sensor_value_to_double(&accel[2]);
    /* gyro: Zephyr delivers rad/s; HAR expects deg/s */
    *gx = (float)sensor_value_to_double(&gyro[0]) * 57.2957795f;
    *gy = (float)sensor_value_to_double(&gyro[1]) * 57.2957795f;
    *gz = (float)sensor_value_to_double(&gyro[2]) * 57.2957795f;
    return 0;
}}

/* ---------- Main thread ---------- */

void main(void)
{{
    LOG_INF("HAR v2 — Zephyr RTOS");
    LOG_INF("Model: %d classes | Window: %d @ %d Hz",
            HAR_NUM_CLASSES, HAR_WINDOW_SIZE, HAR_SAMPLE_RATE);

    if (!device_is_ready(imu_dev)) {{
        LOG_ERR("IMU not ready — check device tree");
        return;
    }}

    har_init();

    for (;;) {{
        float ax, ay, az, gx, gy, gz;

        if (read_one_sample(&ax, &ay, &az, &gx, &gy, &gz) != 0) {{
            k_sleep(K_SECONDS(1));
            continue;
        }}

        /* Fill rolling window */
        sensor_window[sample_idx][0] = ax;
        sensor_window[sample_idx][1] = ay;
        sensor_window[sample_idx][2] = az;
        sensor_window[sample_idx][3] = gx;
        sensor_window[sample_idx][4] = gy;
        sensor_window[sample_idx][5] = gz;
        sample_idx++;

        if (sample_idx >= HAR_WINDOW_SIZE) {{
            window_ready = true;
            sample_idx   = 0;
        }}

        if (window_ready) {{
            har_result_t result;
            har_classify((const float (*)[HAR_N_CHANNELS])sensor_window, &result);

            last_activity = (result.predicted_class >= 0)
                            ? har_get_class_name(result.predicted_class)
                            : "unknown";

            /* Debug line — ignored by Device Test CSV parser */
            printk("# PRED: class=%d conf=%.4f name=%s\\n",
                   result.predicted_class,
                   (double)result.confidence,
                   last_activity);

            window_ready = false;
        }}

        /* CSV output: aX,aY,aZ,gX,gY,gZ[,activity] */
        if (last_activity != NULL)
            printk("%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%s\\n",
                   (double)ax, (double)ay, (double)az,
                   (double)gx, (double)gy, (double)gz,
                   last_activity);
        else
            printk("%.4f,%.4f,%.4f,%.4f,%.4f,%.4f\\n",
                   (double)ax, (double)ay, (double)az,
                   (double)gx, (double)gy, (double)gz);

        k_sleep(K_MSEC({sample_interval_ms}));
    }}
}}
"""

    # ------------------------------------------------------------------
    # CMakeLists.txt
    # ------------------------------------------------------------------

    def _cmake(self) -> str:
        return f"""\
cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{{ZEPHYR_BASE}})
project(har_inference)

target_sources(app PRIVATE
    main.c
    har_features.cpp
    har_model.cpp
    har_classifier.cpp
)

target_include_directories(app PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}})
"""

    # ------------------------------------------------------------------
    # prj.conf
    # ------------------------------------------------------------------

    def _prj_conf(self) -> str:
        return """\
# HAR Inference — Zephyr project configuration
CONFIG_LOG=y
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y
# Increase stack size for feature extraction
CONFIG_MAIN_STACK_SIZE=4096
"""
